# Generated by Django 5.2.6 on 2025-10-01 15:54

import django.db.models.deletion
import escuelaweb.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnhoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Año Escolar',
                'verbose_name_plural': 'Años Escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('parentesco', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Tutor', 'Tutor'), ('Otro', 'Otro')], default='Otro', max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Director', 'Director'), ('Secretaria', 'Secretaria'), ('Administrador', 'Administrador'), ('Coordinador', 'Coordinador'), ('Bibliotecario', 'Bibliotecario'), ('Psicologo', 'Psicólogo'), ('Otro', 'Otro')], default='Estudiante', max_length=20)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=escuelaweb.models.user_profile_picture_path)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Graduado', 'Graduado'), ('Retirado', 'Retirado')], default='Activo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activation_token', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('anho_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='escuelaweb.anhoescolar')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_impartidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'anho_escolar')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='escuelaweb.curso')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_impartidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_p1', models.FloatField(blank=True, null=True)),
                ('com_p2', models.FloatField(blank=True, null=True)),
                ('com_p3', models.FloatField(blank=True, null=True)),
                ('com_p4', models.FloatField(blank=True, null=True)),
                ('log_p1', models.FloatField(blank=True, null=True)),
                ('log_p2', models.FloatField(blank=True, null=True)),
                ('log_p3', models.FloatField(blank=True, null=True)),
                ('log_p4', models.FloatField(blank=True, null=True)),
                ('cie_p1', models.FloatField(blank=True, null=True)),
                ('cie_p2', models.FloatField(blank=True, null=True)),
                ('cie_p3', models.FloatField(blank=True, null=True)),
                ('cie_p4', models.FloatField(blank=True, null=True)),
                ('eti_p1', models.FloatField(blank=True, null=True)),
                ('eti_p2', models.FloatField(blank=True, null=True)),
                ('eti_p3', models.FloatField(blank=True, null=True)),
                ('eti_p4', models.FloatField(blank=True, null=True)),
                ('anho_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escuelaweb.anhoescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escuelaweb.materia')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='estudiantes',
            field=models.ManyToManyField(related_name='materias_inscritas', through='escuelaweb.Matricula', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Otro', 'Otro')], default='Otro', max_length=10)),
                ('cedula', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('rne', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
                ('contacto_emergencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto_emergencia_de', to='escuelaweb.tutor')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madre_de', to='escuelaweb.tutor')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padre_de', to='escuelaweb.tutor')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_de', to='escuelaweb.tutor')),
            ],
        ),
    ]
