# Generated by Django 5.2.7 on 2025-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='rp_p1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp_p2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp_p3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp_p4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
