# Generated by Django 5.2.7 on 2025-12-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0005_matricula_ex_com_matricula_ex_esp_matricula_ex_ext'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estudiante'], name='escuelaweb__estudia_f27026_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['materia'], name='escuelaweb__materia_8952b1_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['anho_escolar'], name='escuelaweb__anho_es_74454c_idx'),
        ),
    ]
