# Generated by Django 5.2.7 on 2026-01-14 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0010_customuser_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='jueves',
            field=models.BooleanField(default=False, verbose_name='Jueves'),
        ),
        migrations.AddField(
            model_name='materia',
            name='lunes',
            field=models.BooleanField(default=False, verbose_name='Lunes'),
        ),
        migrations.AddField(
            model_name='materia',
            name='martes',
            field=models.BooleanField(default=False, verbose_name='Martes'),
        ),
        migrations.AddField(
            model_name='materia',
            name='miercoles',
            field=models.BooleanField(default=False, verbose_name='Miércoles'),
        ),
        migrations.AddField(
            model_name='materia',
            name='viernes',
            field=models.BooleanField(default=False, verbose_name='Viernes'),
        ),
        migrations.AlterField(
            model_name='asistenciapersonal',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario (Estudiante, Profesor o personal administrativo)', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_personal', to=settings.AUTH_USER_MODEL),
        ),
    ]
