# Generated by Django 6.0.1 on 2026-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0013_factura_detallefactura_pagofactura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAnulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de Anulación',
                'verbose_name_plural': 'Códigos de Anulación',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
