# Generated by Django 6.0.1 on 2026-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0016_articulo_codigo_barras_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articulo',
            name='escuelaweb__codigo_74c1f8_idx',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', help_text='Código de barras para lector óptico', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='codigo',
        ),
    ]
