# Generated by Django 6.0.1 on 2026-01-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0021_auto_20260122_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mes numérico (1-12)')),
                ('anio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_pagado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('anho_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades', to='escuelaweb.anhoescolar')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuelaweb.conceptopago')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensualidades_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensualidades', to='escuelaweb.factura')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('estudiante', 'anho_escolar', 'mes', 'anio')},
            },
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='mensualidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='escuelaweb.mensualidad'),
        ),
    ]
