# Generated by Django 6.0.1 on 2026-01-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0025_alter_tarifaestudiante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptopago',
            name='tipo',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad'), ('inscripcion', 'Inscripción'), ('transporte', 'Transporte'), ('articulo', 'Artículo/Papelería'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='mensualidad', max_length=20),
        ),
    ]
