# Generated by Django 6.0.1 on 2026-01-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0026_alter_conceptopago_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptopago',
            name='es_estandar',
            field=models.BooleanField(default=False, help_text='Se asignará automáticamente a nuevos estudiantes', verbose_name='Tarifa Estándar'),
        ),
    ]
