# Generated by Django 6.0.1 on 2026-01-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0027_conceptopago_es_estandar'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='categoria',
            field=models.CharField(choices=[('periodo', 'Por Períodos'), ('modular', 'Modular')], default='periodo', help_text='Por Períodos: calificaciones por período (P1, P2, P3). Modular: evaluación continua.', max_length=20, verbose_name='Categoría de Evaluación'),
        ),
    ]
