# Generated by Django 6.0.1 on 2026-01-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0028_materia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ra_1',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 1 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_10',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 10 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_2',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 2 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_3',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 3 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_4',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 4 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_5',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 5 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_6',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 6 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_7',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 7 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_8',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 8 (%)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_9',
            field=models.FloatField(blank=True, null=True, verbose_name='RA 9 (%)'),
        ),
    ]
