# Generated by Django 6.0.1 on 2026-01-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0029_matricula_ra_1_matricula_ra_10_matricula_ra_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='ra_configuracion',
            field=models.JSONField(blank=True, help_text='Configuración de RA: cantidad y valores en % (solo modular)', null=True),
        ),
    ]
