# Generated by Django 6.0.1 on 2026-03-07 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0033_grupofamiliar_dia_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único de la cuenta (ej: 1.1.01.001)', max_length=20, unique=True, verbose_name='Código de Cuenta')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la cuenta contable', max_length=200, verbose_name='Nombre de la Cuenta')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del uso de esta cuenta', null=True, verbose_name='Descripción')),
                ('tipo_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('CAPITAL', 'Capital / Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo')], help_text='Clasificación principal de la cuenta', max_length=10, verbose_name='Tipo de Cuenta')),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], help_text='Naturaleza contable de la cuenta (Deudora o Acreedora)', max_length=10, verbose_name='Naturaleza')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel jerárquico de la cuenta (1=Mayor, 2=Submayer, 3=Auxiliar, etc.)', verbose_name='Nivel')),
                ('es_detalle', models.BooleanField(default=True, help_text='Indica si la cuenta acepta movimientos directos (True) o es solo agrupadora (False)', verbose_name='Es Cuenta de Detalle')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la cuenta está activa para uso', verbose_name='Activo')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo inicial de la cuenta al inicio del período contable', max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo actual de la cuenta', max_digits=15, verbose_name='Saldo Actual')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('requiere_centro_costo', models.BooleanField(default=False, help_text='Indica si los movimientos en esta cuenta requieren especificar un centro de costo', verbose_name='Requiere Centro de Costo')),
                ('requiere_tercero', models.BooleanField(default=False, help_text='Indica si los movimientos requieren especificar un tercero (cliente/proveedor)', verbose_name='Requiere Tercero')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('cuenta_padre', models.ForeignKey(blank=True, help_text='Cuenta superior en la jerarquía', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='escuelaweb.plancuentas', verbose_name='Cuenta Padre')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='escuelaweb__codigo_f90559_idx'), models.Index(fields=['tipo_cuenta'], name='escuelaweb__tipo_cu_fd24c3_idx'), models.Index(fields=['activo'], name='escuelaweb__activo_c0e861_idx'), models.Index(fields=['es_detalle'], name='escuelaweb__es_deta_98ebfb_idx')],
            },
        ),
    ]
