# Generated by Django 6.0.1 on 2026-03-24 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0037_listacotejo_evaluacionlistacotejo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaestudiante',
            name='dia_vencimiento',
            field=models.IntegerField(blank=True, default=None, help_text='Día del mes para vencimiento de pago (1-31). Si no se especifica, usa el del grupo familiar.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
