# Generated by Django 6.0.1 on 2026-03-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0039_customuser_dia_vencimiento_individual'),
    ]

    operations = [
    ]
