# Generated by Django 6.0.1 on 2026-03-25 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0040_auto_20260324_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='descuento_individual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento para este estudiante (solo si no está en un grupo familiar)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Individual (%)'),
        ),
    ]
