# Generated by Django 6.0.1 on 2026-03-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0041_add_descuento_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('inicio_anho', 'Inicio de Año Escolar'), ('inicio_periodo_1', 'Inicio Primer Período'), ('inicio_periodo_2', 'Inicio Segundo Período'), ('inicio_periodo_3', 'Inicio Tercer Período'), ('inicio_periodo_4', 'Inicio Cuarto Período'), ('inicio_unidad', 'Inicio de Unidad Didáctica')], max_length=20, verbose_name='Período de Aplicación')),
                ('competencia', models.CharField(blank=True, help_text='Ej: Competencia Comunicativa, Pensamiento Lógico, Resolución de Problemas', max_length=255, null=True, verbose_name='Competencia a Evaluar')),
                ('indicadores', models.TextField(blank=True, help_text='Lista de indicadores de logro que se evaluarán', null=True, verbose_name='Indicadores de Logro')),
                ('fecha_aplicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aplicación')),
                ('instrumento', models.CharField(choices=[('prueba_escrita', 'Prueba Escrita'), ('prueba_oral', 'Prueba Oral'), ('observacion', 'Observación Directa'), ('practica', 'Prueba Práctica'), ('mixta', 'Mixta')], default='prueba_escrita', max_length=20, verbose_name='Tipo de Instrumento')),
                ('observaciones', models.TextField(blank=True, help_text='Anotaciones adicionales sobre la evaluación', null=True, verbose_name='Observaciones/Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_diagnosticas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_diagnosticas', to='escuelaweb.materia', verbose_name='Materia/Asignatura')),
            ],
            options={
                'verbose_name': 'Evaluación Diagnóstica',
                'verbose_name_plural': 'Evaluaciones Diagnósticas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
