# Generated by Django 6.0.1 on 2026-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0046_alter_calificacioncriterio_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(help_text='Nombre oficial de la institución educativa', max_length=200, verbose_name='Nombre de la Escuela')),
                ('rnc', models.CharField(blank=True, help_text='Registro Nacional del Contribuyente', max_length=20, null=True, verbose_name='RNC')),
                ('direccion', models.TextField(blank=True, help_text='Dirección física de la escuela', null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono principal de contacto', max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Email institucional', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('sitio_web', models.URLField(blank=True, help_text='URL del sitio web de la institución', null=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, help_text='Logo oficial de la institución (tamaño recomendado: 200x200px)', null=True, upload_to='escuela/logos/', verbose_name='Logo')),
                ('director_nombre', models.CharField(blank=True, help_text='Nombre completo del director(a)', max_length=200, null=True, verbose_name='Nombre del Director')),
                ('director_firma', models.ImageField(blank=True, help_text='Imagen de la firma del director (fondo transparente)', null=True, upload_to='escuela/firmas/', verbose_name='Firma del Director')),
                ('lema', models.CharField(blank=True, help_text='Lema o eslogan de la institución', max_length=300, null=True, verbose_name='Lema Institucional')),
                ('mision', models.TextField(blank=True, help_text='Declaración de la misión institucional', null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, help_text='Declaración de la visión institucional', null=True, verbose_name='Visión')),
                ('codigo_centro', models.CharField(blank=True, help_text='Código oficial asignado por el MINERD u otra autoridad', max_length=50, null=True, verbose_name='Código del Centro')),
                ('distrito_educativo', models.CharField(blank=True, help_text='Distrito educativo al que pertenece', max_length=100, null=True, verbose_name='Distrito Educativo')),
                ('regional_educativa', models.CharField(blank=True, help_text='Regional educativa a la que pertenece', max_length=100, null=True, verbose_name='Regional Educativa')),
                ('nivel_educativo', models.CharField(blank=True, help_text='Ej: Inicial, Básica, Media, Técnico-Profesional', max_length=100, null=True, verbose_name='Nivel Educativo')),
                ('modalidad', models.CharField(blank=True, help_text='Ej: General, Técnico-Profesional, Artes', max_length=100, null=True, verbose_name='Modalidad')),
                ('horario_atencion', models.CharField(blank=True, help_text='Ej: Lunes a Viernes 7:00 AM - 4:00 PM', max_length=200, null=True, verbose_name='Horario de Atención')),
                ('anho_fundacion', models.IntegerField(blank=True, help_text='Año en que fue fundada la institución', null=True, verbose_name='Año de Fundación')),
                ('pie_pagina_reportes', models.TextField(blank=True, help_text='Texto que aparecerá al pie de los reportes oficiales', null=True, verbose_name='Pie de Página para Reportes')),
                ('mostrar_logo_reportes', models.BooleanField(default=True, help_text='Activar/desactivar el logo en los reportes', verbose_name='Mostrar Logo en Reportes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de la Escuela',
                'verbose_name_plural': 'Configuración de la Escuela',
            },
        ),
    ]
