# Generated by Django 6.0.1 on 2026-04-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0050_matricula_cie_rp1_matricula_cie_rp2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Materia asociada (opcional para rúbricas genéricas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='escuelaweb.materia', verbose_name='Materia/Asignatura'),
        ),
    ]
