# Generated by Django 6.0.1 on 2026-05-08 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0051_make_rubrica_materia_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Escuela')),
                ('nombre_corto', models.SlugField(help_text="Ejemplo: 'colegiosantiago' para colegiosantiago.escuelaenlinea.com", unique=True, validators=[django.core.validators.RegexValidator(message='Solo letras minúsculas, números y guiones', regex='^[a-z0-9-]+$')], verbose_name='Nombre Corto (para subdominios)')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección Física')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('max_usuarios', models.IntegerField(default=500, verbose_name='Máximo de Usuarios')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escuelas/logos/', verbose_name='Logo de la Escuela')),
                ('color_primario', models.CharField(default='#007bff', help_text='Formato: #007bff', max_length=7, verbose_name='Color Primario (Hex)')),
                ('color_secundario', models.CharField(default='#6c757d', help_text='Formato: #6c757d', max_length=7, verbose_name='Color Secundario (Hex)')),
                ('plan', models.CharField(choices=[('prueba', 'Prueba (30 días)'), ('basico', 'Básico'), ('profesional', 'Profesional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='prueba', max_length=20, verbose_name='Plan')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('dominio_principal', models.CharField(blank=True, help_text='Ejemplo: colegiosantiago.escuelaenlinea.com', max_length=100, verbose_name='Dominio Principal')),
                ('dominios_adicionales', models.TextField(blank=True, help_text='Un dominio por línea', verbose_name='Dominios Adicionales')),
                ('anho_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuela_con_anho_actual', to='escuelaweb.anhoescolar', verbose_name='Año Escolar Actual')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'ordering': ['nombre'],
            },
        ),
    ]
