# Generated by Django 6.0.1 on 2026-05-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0055_articulo_escuela_asientocontable_escuela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistenciapersonal',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_personal', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaarticulo',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_articulo', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigoanulacion',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_anulacion', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleasiento',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_asiento', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_diagnosticas', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='listas_cotejo', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagofactura',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_factura', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plan_cuentas', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rubricas', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_estudiantes', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarifaestudiante',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_estudiante', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terminalestudiante',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='terminales_estudiantes', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_pos', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tutores', to='escuelaweb.escuela', verbose_name='Escuela'),
            preserve_default=False,
        ),
    ]
