# Generated by Django 4.2.17 on 2026-05-08 22:06

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0056_alter_articulo_escuela_alter_asientocontable_escuela_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Institución')),
                ('nombre_corto', models.CharField(help_text='Se usará como subdominio: nombre-corto.escuelaenlinea.com', max_length=50, unique=True, verbose_name='Nombre Corto (Subdominio)')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('plan', models.CharField(choices=[('prueba', 'Prueba (30 días)'), ('basico', 'Básico'), ('profesional', 'Profesional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='prueba', max_length=20, verbose_name='Plan de Suscripción')),
                ('max_usuarios', models.IntegerField(default=50, verbose_name='Máximo de Usuarios')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escuela/logos/', verbose_name='Logo')),
                ('color_primario', models.CharField(default='#007bff', max_length=7, verbose_name='Color Primario')),
                ('color_secundario', models.CharField(default='#6c757d', max_length=7, verbose_name='Color Secundario')),
            ],
            options={
                'verbose_name': 'Escuela (Tenant)',
                'verbose_name_plural': 'Escuelas (Tenants)',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='escuelaweb.client')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
