# Generated by Django 4.2.17 on 2026-05-10 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelaweb', '0060_registroescuelaattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesamiento'), ('COMPLETADO', 'Completado Exitosamente'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], max_length=20, verbose_name='Estado del Pago')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Payment Intent ID')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, verbose_name='Invoice ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, verbose_name='Charge ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Pago')),
                ('fecha_procesado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Procesamiento')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Factura')),
                ('factura_url', models.URLField(blank=True, verbose_name='URL de Factura')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata Adicional')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['-fecha_procesado'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('tipo', models.CharField(choices=[('BASICO', 'Básico - Hasta 50 usuarios'), ('ESTANDAR', 'Estándar - Hasta 200 usuarios'), ('PROFESIONAL', 'Profesional - Hasta 500 usuarios'), ('EMPRESARIAL', 'Empresarial - Sin límite')], max_length=20, unique=True, verbose_name='Tipo de Plan')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual (USD)')),
                ('precio_anual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Anual (USD)')),
                ('max_usuarios', models.IntegerField(default=50, help_text='0 = ilimitado', verbose_name='Máximo de Usuarios')),
                ('max_estudiantes', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Máximo de Estudiantes')),
                ('permite_reportes_avanzados', models.BooleanField(default=False, verbose_name='Reportes Avanzados')),
                ('permite_integracion_api', models.BooleanField(default=False, verbose_name='Integración API')),
                ('permite_multiples_sedes', models.BooleanField(default=False, verbose_name='Múltiples Sedes')),
                ('soporte_prioritario', models.BooleanField(default=False, verbose_name='Soporte Prioritario')),
                ('stripe_price_id_mensual', models.CharField(blank=True, help_text='ID del precio mensual en Stripe', max_length=100)),
                ('stripe_price_id_anual', models.CharField(blank=True, help_text='ID del precio anual en Stripe', max_length=100)),
                ('activo', models.BooleanField(default=True, verbose_name='Plan Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['orden', 'precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('TRIAL', 'Periodo de Prueba (30 días)'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('SUSPENDIDA', 'Suspendida por falta de pago')], default='TRIAL', max_length=20, verbose_name='Estado')),
                ('periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20, verbose_name='Periodo de Facturación')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_trial', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin de Prueba')),
                ('fecha_proximo_pago', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Pago')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Subscription ID')),
                ('metodo_pago_tipo', models.CharField(blank=True, max_length=20, verbose_name='Tipo de Tarjeta')),
                ('metodo_pago_ultimo4', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
                ('auto_renovacion', models.BooleanField(default=True, verbose_name='Renovación Automática')),
                ('notificacion_vencimiento_enviada', models.BooleanField(default=False, verbose_name='Notificación Enviada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Administrativas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='anhoescolar',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'AÃ±o Escolar', 'verbose_name_plural': 'AÃ±os Escolares'},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['nombre'], 'verbose_name': 'ArtÃ\xadculo', 'verbose_name_plural': 'ArtÃ\xadculos'},
        ),
        migrations.AlterModelOptions(
            name='calificacioncotejo',
            options={'ordering': ['estudiante', 'criterio__orden'], 'verbose_name': 'CalificaciÃ³n de Cotejo', 'verbose_name_plural': 'Calificaciones de Cotejo'},
        ),
        migrations.AlterModelOptions(
            name='calificacioncriterio',
            options={'ordering': ['criterio__orden'], 'verbose_name': 'CalificaciÃ³n de Criterio', 'verbose_name_plural': 'Calificaciones de Criterios'},
        ),
        migrations.AlterModelOptions(
            name='categoriaarticulo',
            options={'ordering': ['nombre'], 'verbose_name': 'CategorÃ\xada de ArtÃ\xadculo', 'verbose_name_plural': 'CategorÃ\xadas de ArtÃ\xadculos'},
        ),
        migrations.AlterModelOptions(
            name='codigoanulacion',
            options={'ordering': ['-anio', '-mes'], 'verbose_name': 'CÃ³digo de AnulaciÃ³n', 'verbose_name_plural': 'CÃ³digos de AnulaciÃ³n'},
        ),
        migrations.AlterModelOptions(
            name='configuracionescuela',
            options={'verbose_name': 'ConfiguraciÃ³n de la Escuela', 'verbose_name_plural': 'ConfiguraciÃ³n de la Escuela'},
        ),
        migrations.AlterModelOptions(
            name='criteriorubrica',
            options={'ordering': ['rubrica', 'orden', 'id'], 'verbose_name': 'Criterio de RÃºbrica', 'verbose_name_plural': 'Criterios de RÃºbrica'},
        ),
        migrations.AlterModelOptions(
            name='evaluaciondiagnostica',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'EvaluaciÃ³n DiagnÃ³stica', 'verbose_name_plural': 'Evaluaciones DiagnÃ³sticas'},
        ),
        migrations.AlterModelOptions(
            name='evaluacionlistacotejo',
            options={'ordering': ['-fecha_evaluacion'], 'verbose_name': 'EvaluaciÃ³n con Lista de Cotejo', 'verbose_name_plural': 'Evaluaciones con Listas de Cotejo'},
        ),
        migrations.AlterModelOptions(
            name='evaluacionrubrica',
            options={'ordering': ['-fecha_evaluacion'], 'verbose_name': 'EvaluaciÃ³n con RÃºbrica', 'verbose_name_plural': 'Evaluaciones con RÃºbrica'},
        ),
        migrations.AlterModelOptions(
            name='niveldesempeno',
            options={'ordering': ['-puntaje'], 'verbose_name': 'Nivel de DesempeÃ±o', 'verbose_name_plural': 'Niveles de DesempeÃ±o'},
        ),
        migrations.AlterModelOptions(
            name='resultadoevaluaciondiagnostica',
            options={'ordering': ['estudiante__first_name', 'estudiante__last_name'], 'verbose_name': 'Resultado de EvaluaciÃ³n DiagnÃ³stica', 'verbose_name_plural': 'Resultados de Evaluaciones DiagnÃ³sticas'},
        ),
        migrations.AlterModelOptions(
            name='resumenevaluacioncotejo',
            options={'ordering': ['estudiante__first_name', 'estudiante__last_name'], 'verbose_name': 'Resumen de EvaluaciÃ³n de Cotejo', 'verbose_name_plural': 'ResÃºmenes de Evaluaciones de Cotejo'},
        ),
        migrations.AlterModelOptions(
            name='rubrica',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'RÃºbrica', 'verbose_name_plural': 'RÃºbricas'},
        ),
        migrations.AlterModelOptions(
            name='terminalestudiante',
            options={'verbose_name': 'Terminal-Estudiante', 'verbose_name_plural': 'Terminales-Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='transaccionpos',
            options={'verbose_name': 'Transacción POS', 'verbose_name_plural': 'Transacciones POS'},
        ),
        migrations.AlterModelOptions(
            name='twofactorauth',
            options={'verbose_name': 'AutenticaciÃ³n de Dos Factores', 'verbose_name_plural': 'Autenticaciones de Dos Factores'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'SesiÃ³n de Usuario', 'verbose_name_plural': 'Sesiones de Usuario'},
        ),
        migrations.RemoveIndex(
            model_name='terminalestudiante',
            name='escuelaweb__termina_c3fec8_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaccionpos',
            name='escuelaweb__transac_dab7b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaccionpos',
            name='escuelaweb__proveed_6196a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaccionpos',
            name='escuelaweb__estudia_36b328_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaccionpos',
            name='escuelaweb__estado_4e1940_idx',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', help_text='CÃ³digo de barras para lector Ã³ptico', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='concepto',
            field=models.TextField(help_text='DescripciÃ³n general del asiento contable', verbose_name='Concepto/DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='fecha_contabilizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se contabilizÃ³ el asiento', null=True, verbose_name='Fecha de ContabilizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='RazÃ³n por la cual se anulÃ³ el asiento', null=True, verbose_name='Motivo de AnulaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='numero_asiento',
            field=models.CharField(db_index=True, help_text='NÃºmero Ãºnico del asiento (ej: ASI-2026-001)', max_length=20, unique=True, verbose_name='NÃºmero de Asiento'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia externa (nÃºmero de factura, recibo, etc.)', max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo_asiento',
            field=models.CharField(choices=[('APERTURA', 'Asiento de Apertura'), ('DIARIO', 'Asiento de Diario'), ('AJUSTE', 'Asiento de Ajuste'), ('CIERRE', 'Asiento de Cierre'), ('TRASPASO', 'Asiento de Traspaso')], default='DIARIO', help_text='ClasificaciÃ³n del asiento contable', max_length=15, verbose_name='Tipo de Asiento'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='total_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suma total de los crÃ©ditos', max_digits=15, verbose_name='Total CrÃ©dito'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='total_debito',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suma total de los dÃ©bitos', max_digits=15, verbose_name='Total DÃ©bito'),
        ),
        migrations.AlterField(
            model_name='asistenciapersonal',
            name='registrado_por',
            field=models.ForeignKey(help_text='Usuario que registrÃ³ la asistencia (Secretaria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_personal_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificacioncotejo',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='escuelaweb.evaluacionlistacotejo', verbose_name='EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='calificacioncotejo',
            name='fecha_calificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de CalificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='calificacioncotejo',
            name='observacion',
            field=models.TextField(blank=True, help_text='Comentario especÃ\xadfico sobre este criterio para este estudiante', null=True, verbose_name='ObservaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='calificacioncotejo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor segÃºn el tipo de criterio', max_digits=6, null=True, verbose_name='Valor Obtenido'),
        ),
        migrations.AlterField(
            model_name='calificacioncriterio',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='escuelaweb.evaluacionrubrica', verbose_name='EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='calificacioncriterio',
            name='fecha_calificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de CalificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='calificacioncriterio',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Comentarios especÃ\xadficos sobre el desempeÃ±o en este criterio', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='conceptopago',
            name='es_estandar',
            field=models.BooleanField(default=False, help_text='Se asignarÃ¡ automÃ¡ticamente a nuevos estudiantes', verbose_name='Tarifa EstÃ¡ndar'),
        ),
        migrations.AlterField(
            model_name='conceptopago',
            name='tipo',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad'), ('inscripcion', 'InscripciÃ³n'), ('transporte', 'Transporte'), ('articulo', 'ArtÃ\xadculo/PapelerÃ\xada'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='mensualidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='anho_fundacion',
            field=models.IntegerField(blank=True, help_text='AÃ±o en que fue fundada la instituciÃ³n', null=True, verbose_name='AÃ±o de FundaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='codigo_centro',
            field=models.CharField(blank=True, help_text='CÃ³digo oficial asignado por el MINERD u otra autoridad', max_length=50, null=True, verbose_name='CÃ³digo del Centro'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='direccion',
            field=models.TextField(blank=True, help_text='DirecciÃ³n fÃ\xadsica de la escuela', null=True, verbose_name='DirecciÃ³n'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='email',
            field=models.EmailField(blank=True, help_text='Email institucional', max_length=254, null=True, verbose_name='Correo ElectrÃ³nico'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima ActualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de CreaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='horario_atencion',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes 7:00 AM - 4:00 PM', max_length=200, null=True, verbose_name='Horario de AtenciÃ³n'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='lema',
            field=models.CharField(blank=True, help_text='Lema o eslogan de la instituciÃ³n', max_length=300, null=True, verbose_name='Lema Institucional'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo oficial de la instituciÃ³n (tamaÃ±o recomendado: 200x200px)', null=True, upload_to='escuela/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='mision',
            field=models.TextField(blank=True, help_text='DeclaraciÃ³n de la misiÃ³n institucional', null=True, verbose_name='MisiÃ³n'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='modalidad',
            field=models.CharField(blank=True, help_text='Ej: General, TÃ©cnico-Profesional, Artes', max_length=100, null=True, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='nivel_educativo',
            field=models.CharField(blank=True, help_text='Ej: Inicial, BÃ¡sica, Media, TÃ©cnico-Profesional', max_length=100, null=True, verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='nombre_escuela',
            field=models.CharField(help_text='Nombre oficial de la instituciÃ³n educativa', max_length=200, verbose_name='Nombre de la Escuela'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='pie_pagina_reportes',
            field=models.TextField(blank=True, help_text='Texto que aparecerÃ¡ al pie de los reportes oficiales', null=True, verbose_name='Pie de PÃ¡gina para Reportes'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='URL del sitio web de la instituciÃ³n', null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='telefono',
            field=models.CharField(blank=True, help_text='TelÃ©fono principal de contacto', max_length=50, null=True, verbose_name='TelÃ©fono'),
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='vision',
            field=models.TextField(blank=True, help_text='DeclaraciÃ³n de la visiÃ³n institucional', null=True, verbose_name='VisiÃ³n'),
        ),
        migrations.AlterField(
            model_name='criteriolistacotejo',
            name='descripcion',
            field=models.CharField(help_text='Ej: Completo las actividades en clase', max_length=300, verbose_name='DescripciÃ³n del Criterio'),
        ),
        migrations.AlterField(
            model_name='criteriolistacotejo',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de apariciÃ³n en la lista (menor nÃºmero = primero)', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='criteriolistacotejo',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Puntos que vale este criterio', max_digits=5, verbose_name='Puntaje MÃ¡ximo'),
        ),
        migrations.AlterField(
            model_name='criteriolistacotejo',
            name='tipo_criterio',
            field=models.CharField(choices=[('binario', 'Binario (âœ“/âœ— - SÃ\xad/No)'), ('numerico', 'NumÃ©rico (0-10)'), ('escala_5', 'Escala 1-5'), ('escala_3', 'Escala 1-3'), ('porcentaje', 'Porcentaje (0-100%)')], default='binario', max_length=15, verbose_name='Tipo de Criterio'),
        ),
        migrations.AlterField(
            model_name='criteriorubrica',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n detallada de quÃ© se evaluarÃ¡ en este criterio', null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='criteriorubrica',
            name='nombre',
            field=models.CharField(help_text='Ej: Contenido y Profundidad, OrganizaciÃ³n, PresentaciÃ³n Visual', max_length=255, verbose_name='Nombre del Criterio'),
        ),
        migrations.AlterField(
            model_name='criteriorubrica',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de visualizaciÃ³n del criterio', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='criteriorubrica',
            name='ponderacion',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Peso del criterio en la evaluaciÃ³n final (ej: 20.00%)', max_digits=5, verbose_name='PonderaciÃ³n (%)'),
        ),
        migrations.AlterField(
            model_name='criteriorubrica',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='escuelaweb.rubrica', verbose_name='RÃºbrica'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='CÃ³digo de barras para ponchar asistencia', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='descuento_individual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento para este estudiante (solo si no estÃ¡ en un grupo familiar)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Individual (%)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dia_vencimiento_individual',
            field=models.IntegerField(default=10, help_text='DÃ\xada del mes para vencimiento de pago (solo si no estÃ¡ en un grupo familiar)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='DÃ\xada de Vencimiento Individual'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrÃ³nico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='porcentaje_mora_individual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de mora para este estudiante (solo si no estÃ¡ en un grupo familiar)', max_digits=5, verbose_name='Porcentaje de Mora Individual (%)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Director', 'Director'), ('Secretaria', 'Secretaria'), ('Administrador', 'Administrador'), ('Coordinador', 'Coordinador'), ('Bibliotecario', 'Bibliotecario'), ('Psicologo', 'PsicÃ³logo'), ('Otro', 'Otro')], default='Estudiante', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleasiento',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto del crÃ©dito', max_digits=15, verbose_name='CrÃ©dito'),
        ),
        migrations.AlterField(
            model_name='detalleasiento',
            name='debito',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto del dÃ©bito', max_digits=15, verbose_name='DÃ©bito'),
        ),
        migrations.AlterField(
            model_name='detalleasiento',
            name='descripcion',
            field=models.CharField(help_text='DescripciÃ³n especÃ\xadfica de este movimiento', max_length=255, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='detalleasiento',
            name='linea',
            field=models.IntegerField(default=1, help_text='NÃºmero de lÃ\xadnea dentro del asiento', verbose_name='LÃ\xadnea'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='articulo',
            field=models.ForeignKey(blank=True, help_text='ArtÃ\xadculo del inventario (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='escuelaweb.articulo'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descripcion',
            field=models.CharField(help_text='DescripciÃ³n del concepto', max_length=255),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='mes',
            field=models.IntegerField(blank=True, help_text='Mes del aÃ±o (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='competencia',
            field=models.CharField(blank=True, help_text='Ej: Competencia Comunicativa, Pensamiento LÃ³gico, ResoluciÃ³n de Problemas', max_length=255, null=True, verbose_name='Competencia a Evaluar'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='fecha_aplicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de AplicaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de CreaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima ModificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='indicadores',
            field=models.TextField(blank=True, help_text='Lista de indicadores de logro que se evaluarÃ¡n', null=True, verbose_name='Indicadores de Logro'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='instrumento',
            field=models.CharField(choices=[('prueba_escrita', 'Prueba Escrita'), ('prueba_oral', 'Prueba Oral'), ('observacion', 'ObservaciÃ³n Directa'), ('practica', 'Prueba PrÃ¡ctica'), ('mixta', 'Mixta')], default='prueba_escrita', max_length=20, verbose_name='Tipo de Instrumento'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Anotaciones adicionales sobre la evaluaciÃ³n', null=True, verbose_name='Observaciones/Notas'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='periodo',
            field=models.CharField(choices=[('inicio_anho', 'Inicio de AÃ±o Escolar'), ('inicio_periodo_1', 'Inicio Primer PerÃ\xadodo'), ('inicio_periodo_2', 'Inicio Segundo PerÃ\xadodo'), ('inicio_periodo_3', 'Inicio Tercer PerÃ\xadodo'), ('inicio_periodo_4', 'Inicio Cuarto PerÃ\xadodo'), ('inicio_unidad', 'Inicio de Unidad DidÃ¡ctica')], max_length=20, verbose_name='PerÃ\xadodo de AplicaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de CreaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='fecha_evaluacion',
            field=models.DateField(verbose_name='Fecha de EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha LÃ\xadmite para Calificar'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima ModificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de PublicaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='incluir_en_promedio',
            field=models.BooleanField(default=False, help_text='Si esta evaluaciÃ³n debe sumarse al promedio de la materia', verbose_name='Incluir en Promedio Final'),
        ),
        migrations.AlterField(
            model_name='evaluacionlistacotejo',
            name='nombre',
            field=models.CharField(help_text='Ej: EvaluaciÃ³n de participaciÃ³n - Marzo 2026', max_length=200, verbose_name='Nombre de la EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalles de la actividad evaluada', null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de CreaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='fecha_evaluacion',
            field=models.DateField(verbose_name='Fecha de EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='periodo',
            field=models.CharField(help_text='Ej: Primer PerÃ\xadodo, Segundo PerÃ\xadodo', max_length=50, verbose_name='PerÃ\xadodo'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='escuelaweb.rubrica', verbose_name='RÃºbrica'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='titulo',
            field=models.CharField(help_text='Nombre descriptivo de la evaluaciÃ³n (ej: Proyecto Final, ExposiciÃ³n Oral)', max_length=200, verbose_name='TÃ\xadtulo de la EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de CrÃ©dito/DÃ©bito'), ('cheque', 'Cheque'), ('mixto', 'Mixto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el grupo familiar estÃ¡ activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='codigo_familia',
            field=models.CharField(db_index=True, help_text='CÃ³digo Ãºnico para identificar la familia (ej: FAM001, GONZALEZ2024)', max_length=50, unique=True, verbose_name='CÃ³digo de Familia'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='dia_vencimiento',
            field=models.IntegerField(default=10, help_text='DÃ\xada del mes en que vencen las mensualidades (1-31)', verbose_name='DÃ\xada de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='notas',
            field=models.TextField(blank=True, help_text='InformaciÃ³n adicional sobre la familia', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='porcentaje_mora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de recargo aplicado cuando el pago estÃ¡ vencido', max_digits=5, verbose_name='Porcentaje de Mora (%)'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TelÃ©fono de Contacto'),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ExpiraciÃ³n'),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, unique=True, verbose_name='DirecciÃ³n IP'),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='PaÃ\xads de Origen'),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='razon',
            field=models.TextField(verbose_name='RazÃ³n del Bloqueo'),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='tipo_bloqueo',
            field=models.CharField(choices=[('MANUAL', 'Bloqueo Manual'), ('AUTO_RATE_LIMIT', 'AutomÃ¡tico - Rate Limit'), ('AUTO_FAILED_LOGIN', 'AutomÃ¡tico - Login Fallido'), ('AUTO_SUSPICIOUS', 'AutomÃ¡tico - Actividad Sospechosa')], default='MANUAL', max_length=30, verbose_name='Tipo de Bloqueo'),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima Actividad'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n detallada del propÃ³sito de esta lista', null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='es_plantilla',
            field=models.BooleanField(default=True, help_text='Si es True, esta lista puede ser utilizada mÃºltiples veces', verbose_name='Es Plantilla Reutilizable'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de CreaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima ModificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='nombre',
            field=models.CharField(help_text='Ej: Lista de cotejo para evaluar la participaciÃ³n', max_length=200, verbose_name='Nombre de la Lista'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='orden_criterios',
            field=models.CharField(choices=[('manual', 'Manual'), ('alfabetico', 'AlfabÃ©tico')], default='manual', max_length=20, verbose_name='Orden de Criterios'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Puntaje mÃ¡ximo que se puede obtener (usualmente 10)', max_digits=5, verbose_name='Puntaje Total'),
        ),
        migrations.AlterField(
            model_name='listacotejo',
            name='tipo_evaluacion',
            field=models.CharField(choices=[('actividad', 'Actividad EspecÃ\xadfica'), ('proceso', 'EvaluaciÃ³n de Proceso'), ('proyecto', 'Proyecto'), ('comportamiento', 'EvaluaciÃ³n de Comportamiento'), ('cuaderno', 'EvaluaciÃ³n de Cuaderno'), ('participacion', 'ParticipaciÃ³n'), ('otro', 'Otro')], default='actividad', max_length=20, verbose_name='Tipo de EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='DirecciÃ³n IP'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='razon_fallo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RazÃ³n del fallo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='categoria',
            field=models.CharField(choices=[('periodo', 'Por PerÃ\xadodos'), ('modular', 'Modular')], default='periodo', help_text='Por PerÃ\xadodos: calificaciones por perÃ\xadodo (P1, P2, P3). Modular: evaluaciÃ³n continua.', max_length=20, verbose_name='CategorÃ\xada de EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='miercoles',
            field=models.BooleanField(default=False, verbose_name='MiÃ©rcoles'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='ra_configuracion',
            field=models.JSONField(blank=True, help_text='ConfiguraciÃ³n de RA: cantidad y valores en % (solo modular)', null=True),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='mes',
            field=models.IntegerField(help_text='Mes numÃ©rico (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'DevoluciÃ³n')], max_length=20),
        ),
        migrations.AlterField(
            model_name='niveldesempeno',
            name='descriptor',
            field=models.TextField(help_text='DescripciÃ³n detallada de lo que caracteriza este nivel de desempeÃ±o', verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='niveldesempeno',
            name='nivel',
            field=models.CharField(choices=[('excelente', 'Excelente (5)'), ('muy_bueno', 'Muy Bueno (4)'), ('bueno', 'Bueno (3)'), ('regular', 'Regular (2)'), ('necesita_mejorar', 'Necesita Mejorar (1)')], max_length=20, verbose_name='Nivel de DesempeÃ±o'),
        ),
        migrations.AlterField(
            model_name='niveldesempeno',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, help_text='Puntaje numÃ©rico para este nivel (1-5)', max_digits=5, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='mes',
            field=models.IntegerField(blank=True, help_text='Mes del aÃ±o (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='NÃºmero de referencia/transacciÃ³n', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagofactura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de CrÃ©dito/DÃ©bito'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagofactura',
            name='referencia',
            field=models.CharField(blank=True, help_text='NÃºmero de referencia/transacciÃ³n/cheque', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta estÃ¡ activa para uso', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='codigo',
            field=models.CharField(db_index=True, help_text='CÃ³digo Ãºnico de la cuenta (ej: 1.1.01.001)', max_length=20, unique=True, verbose_name='CÃ³digo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, help_text='Cuenta superior en la jerarquÃ\xada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='escuelaweb.plancuentas', verbose_name='Cuenta Padre'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n detallada del uso de esta cuenta', null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='nivel',
            field=models.IntegerField(default=1, help_text='Nivel jerÃ¡rquico de la cuenta (1=Mayor, 2=Submayer, 3=Auxiliar, etc.)', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo inicial de la cuenta al inicio del perÃ\xadodo contable', max_digits=15, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='tipo_cuenta',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('CAPITAL', 'Capital / Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo')], help_text='ClasificaciÃ³n principal de la cuenta', max_length=10, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='registroescuelaattempt',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='DirecciÃ³n IP'),
        ),
        migrations.AlterField(
            model_name='registroescuelaattempt',
            name='razon_fallo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RazÃ³n del Fallo'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciondiagnostica',
            name='debilidades',
            field=models.TextField(blank=True, help_text='Aspectos que requieren refuerzo o intervenciÃ³n', null=True, verbose_name='Ã\x81reas de Mejora'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciondiagnostica',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='escuelaweb.evaluaciondiagnostica', verbose_name='EvaluaciÃ³n DiagnÃ³stica'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciondiagnostica',
            name='fecha_evaluacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciondiagnostica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima ModificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciondiagnostica',
            name='puntaje_obtenido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje numÃ©rico obtenido (opcional)', max_digits=5, null=True, verbose_name='Puntaje Obtenido'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciondiagnostica',
            name='puntaje_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje total de la evaluaciÃ³n (opcional)', max_digits=5, null=True, verbose_name='Puntaje Total'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciondiagnostica',
            name='recomendaciones',
            field=models.TextField(blank=True, help_text='Estrategias pedagÃ³gicas sugeridas para este estudiante', null=True, verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='resumenevaluacioncotejo',
            name='esta_completo',
            field=models.BooleanField(default=False, verbose_name='EvaluaciÃ³n Completa'),
        ),
        migrations.AlterField(
            model_name='resumenevaluacioncotejo',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='escuelaweb.evaluacionlistacotejo', verbose_name='EvaluaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='resumenevaluacioncotejo',
            name='fecha_calculo',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de CÃ¡lculo'),
        ),
        migrations.AlterField(
            model_name='resumenevaluacioncotejo',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Puntaje MÃ¡ximo'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la rÃºbrica estÃ¡ activa para usar', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n general de la rÃºbrica', null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de CreaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima ModificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Materia asociada (opcional para rÃºbricas genÃ©ricas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='escuelaweb.materia', verbose_name='Materia/Asignatura'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='nombre',
            field=models.CharField(help_text='Ej: EvaluaciÃ³n de Proyecto de Ciencias', max_length=255, verbose_name='Nombre de la RÃºbrica'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='tipo_actividad',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('presentacion', 'PresentaciÃ³n Oral'), ('trabajo_escrito', 'Trabajo Escrito'), ('trabajo_grupo', 'Trabajo en Grupo'), ('experimentacion', 'ExperimentaciÃ³n/PrÃ¡ctica'), ('exposicion', 'ExposiciÃ³n'), ('debate', 'Debate'), ('otro', 'Otro')], default='proyecto', max_length=20, verbose_name='Tipo de Actividad'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='descripcion',
            field=models.TextField(verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISANDO', 'En RevisiÃ³n'), ('RESUELTA', 'Resuelta'), ('FALSA_ALARMA', 'Falsa Alarma'), ('IGNORADA', 'Ignorada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ResoluciÃ³n'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de RevisiÃ³n'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='DirecciÃ³n IP'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='nivel_prioridad',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'CrÃ\xadtica')], default='MEDIUM', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='tipo_alerta',
            field=models.CharField(choices=[('BRUTE_FORCE', 'Intento de Fuerza Bruta'), ('MULTIPLE_FAILED_LOGIN', 'MÃºltiples Intentos Fallidos'), ('SUSPICIOUS_IP', 'IP Sospechosa'), ('UNUSUAL_LOCATION', 'UbicaciÃ³n Inusual'), ('UNUSUAL_TIME', 'Hora Inusual'), ('ACCOUNT_COMPROMISE', 'Posible Cuenta Comprometida'), ('DATA_BREACH', 'Posible FiltraciÃ³n de Datos'), ('PRIVILEGE_ESCALATION', 'Escalada de Privilegios'), ('UNAUTHORIZED_ACCESS', 'Acceso No Autorizado'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de Alerta'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='descripcion',
            field=models.TextField(verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='DirecciÃ³n IP'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='nivel_severidad',
            field=models.CharField(choices=[('INFO', 'InformaciÃ³n'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'CrÃ\xadtico')], default='INFO', max_length=20, verbose_name='Nivel de severidad'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='tipo_evento',
            field=models.CharField(choices=[('LOGIN', 'Login exitoso'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login fallido'), ('PASSWORD_CHANGE', 'Cambio de contraseÃ±a'), ('PASSWORD_RESET', 'Reseteo de contraseÃ±a'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada'), ('ACCOUNT_UNLOCKED', 'Cuenta desbloqueada'), ('PERMISSION_DENIED', 'Permiso denegado'), ('PROFILE_UPDATE', 'ActualizaciÃ³n de perfil'), ('SESSION_EXPIRED', 'SesiÃ³n expirada'), ('2FA_ENABLED', '2FA habilitado'), ('2FA_DISABLED', '2FA deshabilitado'), ('SUSPICIOUS_ACTIVITY', 'Actividad sospechosa'), ('DATA_EXPORT', 'ExportaciÃ³n de datos'), ('ADMIN_ACTION', 'AcciÃ³n administrativa')], max_length=50, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='tarifaestudiante',
            name='concepto',
            field=models.ForeignKey(blank=True, help_text='Solo conceptos de tipo mensualidad, inscripciÃ³n o transporte', limit_choices_to={'tipo__in': ['mensualidad', 'inscripcion', 'transporte']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='escuelaweb.conceptopago'),
        ),
        migrations.AlterField(
            model_name='tarifaestudiante',
            name='dia_vencimiento',
            field=models.IntegerField(blank=True, default=None, help_text='DÃ\xada del mes para vencimiento de pago (1-31). Si no se especifica, usa el del grupo familiar.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='terminalestudiante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='terminalestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='terminalestudiante',
            name='proveedor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='terminalestudiante',
            name='terminal_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='datos_webhook',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='factura_pagada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuelaweb.factura'),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='fecha_procesamiento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='fecha_transaccion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='proveedor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='tarjeta_ultimos_4',
            field=models.CharField(blank=True, default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='terminal_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccionpos',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='CÃ³digos de respaldo'),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de habilitaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='ultimo_uso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ãšltimo uso'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='SesiÃ³n activa'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='fecha_ultima_actividad',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima actividad'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='DirecciÃ³n IP'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40, unique=True, verbose_name='Clave de sesiÃ³n'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='escuelaweb.plan', verbose_name='Plan Actual'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='escuelaweb.client', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='escuelaweb.suscripcion', verbose_name='Suscripción'),
        ),
        migrations.AddIndex(
            model_name='historialpago',
            index=models.Index(fields=['suscripcion', '-fecha_procesado'], name='escuelaweb__suscrip_49ac34_idx'),
        ),
        migrations.AddIndex(
            model_name='historialpago',
            index=models.Index(fields=['estado', '-fecha_procesado'], name='escuelaweb__estado_8b4590_idx'),
        ),
        migrations.AddIndex(
            model_name='historialpago',
            index=models.Index(fields=['stripe_payment_intent_id'], name='escuelaweb__stripe__efc9c1_idx'),
        ),
    ]
