# -*- coding: utf-8 -*-
"""
Django settings for VentasSys project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# IMPORTANTE: Fix de encoding para Windows - DEBE IR ANTES de cualquier otra cosa
try:
    from . import encoding_fix
except ImportError:
    pass

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env con codificación UTF-8 explícita
load_dotenv(os.path.join(BASE_DIR, '.env'), encoding='utf-8')


def get_env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


# ============================================
# DJANGO-TENANTS CONFIGURATION
# ============================================
TENANT_MODEL = "ventasweb.Client"
TENANT_DOMAIN_MODEL = "ventasweb.Domain"

# ============================================
# SEGURIDAD
# ============================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "❌ SECRET_KEY no está configurada. "
        "Añádela a tu archivo .env: SECRET_KEY=tu_clave_secreta_aqui"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# No mostrar todas las URLs en errores 404 (incluso en DEBUG mode)
DEBUG_PROPAGATE_EXCEPTIONS = False

# Hosts permitidos (Multi-Tenant: permitir subdominios)
ALLOWED_HOSTS = get_env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,.localhost,.misventasflash.com')

# Permitir todos los subdominios en desarrollo
if DEBUG:
    ALLOWED_HOSTS += ['.localhost', '*.localhost', '127.0.0.1']

# Entorno de ejecución
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

# CSRF Trusted Origins (para HTTPS)
CSRF_TRUSTED_ORIGINS = get_env_list('CSRF_TRUSTED_ORIGINS')
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost',
        'http://127.0.0.1',
        *[
            f'https://{host}'
            for host in ALLOWED_HOSTS
            if host not in {'localhost', '127.0.0.1'}
        ],
    ]
#https
#=============================================
# Configuraciones HTTPS solo en producción
if not DEBUG and ENVIRONMENT == 'production':
    # Informa a Django que Nginx está manejando el SSL/TLS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Forzar el uso de cookies seguras en producción
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Redirigir cualquier petición HTTP entrante a HTTPS dentro de Django
    SECURE_SSL_REDIRECT = True
# ============================================
# SESIÓN
# ============================================
# Desactivar la cabecera Cross-Origin-Opener-Policy
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', '14400'))  # 4 horas por defecto (fallback)
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.getenv('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'False') == 'True'
SESSION_SAVE_EVERY_REQUEST = os.getenv('SESSION_SAVE_EVERY_REQUEST', 'True') == 'True'  # Renovar sesión en cada request

# Tiempos de sesión por rol (en segundos)
# El middleware RoleBasedSessionMiddleware utilizará estos valores
# Si no están definidos en .env, usará valores predeterminados del middleware

# ============================================
# EMAIL
# ============================================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SITE_URL = os.getenv('SITE_URL', '127.0.0.1:8000')

# ============================================
# AUTENTICACIÓN
# ============================================
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/anhos-escolares/'
LOGOUT_REDIRECT_URL = '/login/'


# Application definition

# Apps compartidas entre todos los tenants (public schema)
SHARED_APPS = [
    'django_tenants',  # Debe ser la primera app
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_recaptcha',
    'django_celery_beat',  # Celery Beat para tareas programadas
    'django_celery_results',  # Resultados de Celery
    'ventasweb',  # Necesario en shared para Client y Domain models
]

# Apps específicas de cada tenant (en su propio schema)
TENANT_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_recaptcha',
    'ventasweb',
]

INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',  # django-tenants PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'ventasweb.security_middleware.RateLimitMiddleware',  # Rate limiting y bloqueo de IPs
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'ventasweb.subscription_middleware.SubscriptionMiddleware',  # Verificación de suscripción - DESHABILITADO TEMPORALMENTE
    'ventasweb.middleware.RoleBasedSessionMiddleware',  # Tiempos de sesión por rol
    'ventasweb.security_middleware.SessionSecurityMiddleware',  # Seguridad de sesiones
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ventasweb.middleware_404.Custom404Middleware',  # Manejador personalizado de 404
]

ROOT_URLCONF = 'VentasSys.urls'
PUBLIC_SCHEMA_URLCONF = 'VentasSys.urls_public'  # URLs para public schema (registro, login)

# Database routers for multi-tenancy
DATABASE_ROUTERS = [
    'django_tenants.routers.TenantSyncRouter',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [os.path.join(BASE_DIR, "ventasweb", "templates")],  # Updated path
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ventasweb.context_processors.school_configuration',
            ],
        },
    },
]

WSGI_APPLICATION = 'VentasSys.wsgi.application'

# ============================================
# DATABASE
# ============================================
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configuración PostgreSQL - Credenciales OBLIGATORIAS desde .env
_db_name = os.getenv('DB_NAME')
_db_user = os.getenv('DB_USER')
_db_password = os.getenv('DB_PASSWORD')

if not all([_db_name, _db_user, _db_password]):
    raise ValueError(
        "❌ Faltan credenciales de base de datos en .env. "
        "Variables requeridas: DB_NAME, DB_USER, DB_PASSWORD"
    )

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',  # Motor con soporte multi-tenant
        'NAME': _db_name,
        'USER': _db_user,
        'PASSWORD': _db_password,
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
            'connect_timeout': 10,
            'options': '-c client_encoding=UTF8',
        },
        'CONN_MAX_AGE': 0,  # No reutilizar conexiones para evitar problemas de encoding
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators





AUTH_USER_MODEL = 'ventasweb.CustomUser'





AUTHENTICATION_BACKENDS = [
    'ventasweb.backends.EmailBackend',  # Autenticación por email
    'django.contrib.auth.backends.ModelBackend',  # Fallback
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-do'  # Español - República Dominicana

TIME_ZONE = 'America/Santo_Domingo'  # Zona horaria República Dominicana (UTC-4)

USE_I18N = True

USE_TZ = True  # Mantener True para usar timezone-aware datetimes

# Character encoding
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Ruta para recolectar archivos estáticos en producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use WhiteNoise to serve static files in development/production when configured
WHITENOISE_MANIFEST_STRICT = False
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# MEDIA FILES
# ============================================
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# ============================================
# CONFIGURACIONES DE SEGURIDAD PARA PRODUCCIÓN
# ============================================

if not DEBUG:
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Otras configuraciones de seguridad
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# ============================================
# GOOGLE reCAPTCHA v2
# ============================================
# Obtener claves de Google reCAPTCHA: https://www.google.com/recaptcha/admin
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')  # clave de testing
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')  # clave de testing

# Configuraciones adicionales de reCAPTCHA
RECAPTCHA_REQUIRED_SCORE = 0.85  # Para reCAPTCHA v3 (no usado con v2)

# Silenciar advertencia de claves de testing en desarrollo
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

# Deshabilitar CAPTCHA en desarrollo si quieres (opcional)
if DEBUG and os.getenv('DISABLE_CAPTCHA_IN_DEV', 'False') == 'True':
    pass  # Ya silenciado arriba


# ============================================
# CONFIGURACIONES DE SEGURIDAD AVANZADAS
# ============================================

# Configuración de bloqueo de cuentas
MAX_LOGIN_ATTEMPTS = int(os.getenv('MAX_LOGIN_ATTEMPTS', '5'))
LOGIN_BLOCK_MINUTES = int(os.getenv('LOGIN_BLOCK_MINUTES', '15'))

# Configuración de alertas de seguridad
SECURITY_ALERTS_ENABLED = os.getenv('SECURITY_ALERTS_ENABLED', 'True') == 'True'
SECURITY_ALERT_EMAIL_RECIPIENTS = get_env_list('SECURITY_ALERT_EMAIL_RECIPIENTS', EMAIL_HOST_USER)

# 2FA Obligatorio para roles específicos
REQUIRE_2FA_FOR_ROLES = get_env_list('REQUIRE_2FA_FOR_ROLES', 'Administrador,Director')

# Configuración de limpieza automática
AUTO_CLEANUP_SESSIONS_DAYS = int(os.getenv('AUTO_CLEANUP_SESSIONS_DAYS', '30'))
AUTO_CLEANUP_LOGS_DAYS = int(os.getenv('AUTO_CLEANUP_LOGS_DAYS', '90'))


# ============================================
# LOGGING
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'ventasweb.security_middleware': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# ============================================
# CONFIGURACIÓN DE POS FÍSICOS (Cardnet, Azul)
# ============================================

# Proveedor de pago principal
PAYMENT_PROVIDER = os.getenv('PAYMENT_PROVIDER', 'cardnet')

# Credenciales Cardnet
CARDNET_API_KEY = os.getenv('CARDNET_API_KEY', '')
CARDNET_MERCHANT_ID = os.getenv('CARDNET_MERCHANT_ID', '')
CARDNET_WEBHOOK_SECRET = os.getenv('CARDNET_WEBHOOK_SECRET', '')
CARDNET_API_URL = os.getenv('CARDNET_API_URL', 'https://sandbox.cardnet.com.do/api')

# Credenciales Azul
AZUL_USER = os.getenv('AZUL_USER', '')
AZUL_PASSWORD = os.getenv('AZUL_PASSWORD', '')
AZUL_STORE_ID = os.getenv('AZUL_STORE_ID', '')
AZUL_WEBHOOK_SECRET = os.getenv('AZUL_WEBHOOK_SECRET', '')
AZUL_API_URL = os.getenv('AZUL_API_URL', 'https://sandbox.azul.com.do')


# ============================================
# STRIPE - SISTEMA DE SUSCRIPCIONES
# ============================================

# Claves de Stripe (obtener en: https://dashboard.stripe.com/apikeys)
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Modo de prueba (True para usar claves de test, False para producción)
STRIPE_TEST_MODE = os.getenv('STRIPE_TEST_MODE', 'True') == 'True'

# URLs para redireccionamiento después del pago
STRIPE_SUCCESS_URL = os.getenv('STRIPE_SUCCESS_URL', 'http://localhost:8000/suscripcion/pago-exitoso/')
STRIPE_CANCEL_URL = os.getenv('STRIPE_CANCEL_URL', 'http://localhost:8000/suscripcion/planes/')

# Moneda por defecto
STRIPE_CURRENCY = os.getenv('STRIPE_CURRENCY', 'usd')

# Validar configuración de Stripe en producción
if not DEBUG and not STRIPE_SECRET_KEY:
    print("⚠️  ADVERTENCIA: STRIPE_SECRET_KEY no está configurada en producción")


# ============================================
# CELERY - SISTEMA DE TAREAS ASÍNCRONAS
# ============================================

# Broker de mensajes (Redis)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'  # Usar django-celery-results

# Configuración de zona horaria
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Serialización
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Configuración de resultados
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 3600  # 1 hora

# Configuración de tareas
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutos (límite suave)

# Configuración de Beat (tareas programadas)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Logging de Celery
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'


# Configuración de impresora POS
AUTO_PRINT_INVOICES = os.getenv('AUTO_PRINT_INVOICES', 'False') == 'True'
POS_PRINTER_ENABLED = os.getenv('POS_PRINTER_ENABLED', 'False') == 'True'
POS_PRINTER_TYPE = os.getenv('POS_PRINTER_TYPE', 'network')  # network, usb, file
POS_PRINTER_NAME = os.getenv('POS_PRINTER_NAME', 'EPSON_TM_T88')

# Impresora en red
POS_PRINTER_IP = os.getenv('POS_PRINTER_IP', '192.168.1.100')
POS_PRINTER_PORT = int(os.getenv('POS_PRINTER_PORT', '9100'))

# Impresora USB
POS_PRINTER_VENDOR_ID = int(os.getenv('POS_PRINTER_VENDOR_ID', '0x04b8'), 16)
POS_PRINTER_PRODUCT_ID = int(os.getenv('POS_PRINTER_PRODUCT_ID', '0x0e15'), 16)

# Impresora a archivo (para pruebas)
POS_PRINTER_PATH = os.getenv('POS_PRINTER_PATH', '/tmp/receipt.txt')

# Envío automático de facturas por email
AUTO_EMAIL_INVOICES = os.getenv('AUTO_EMAIL_INVOICES', 'False') == 'True'


