# Generated by Django 5.2.7 on 2025-11-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0002_matricula_rp_p1_matricula_rp_p2_matricula_rp_p3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='rp_cie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp_eti',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp_log',
            field=models.FloatField(blank=True, null=True),
        ),
    ]

