# Generated by Django 5.2.7 on 2025-11-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0003_matricula_rp_cie_matricula_rp_com_matricula_rp_eti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='rp_cie',
            new_name='cie_rp',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='rp_com',
            new_name='com_rp',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='rp_eti',
            new_name='eti_rp',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='rp_log',
            new_name='log_rp',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='rp_p1',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='rp_p2',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='rp_p3',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='rp_p4',
        ),
    ]

