# Generated by Django 5.2.7 on 2025-11-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0004_rename_rp_cie_matricula_cie_rp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ex_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ex_esp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ex_ext',
            field=models.FloatField(blank=True, null=True),
        ),
    ]

