# Generated by Django 5.2.7 on 2026-01-13 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0008_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('permiso', 'Permiso')], default='presente', max_length=10)),
                ('hora_entrada', models.TimeField(blank=True, help_text='Hora de entrada registrada', null=True)),
                ('hora_salida', models.TimeField(blank=True, help_text='Hora de salida registrada', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró la asistencia (Secretaria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_personal_registradas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Profesor o personal administrativo', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia Personal',
                'verbose_name_plural': 'Asistencias Personal',
                'ordering': ['-fecha', 'usuario__first_name'],
                'indexes': [models.Index(fields=['fecha'], name='escuelaweb__fecha_ec4ae2_idx'), models.Index(fields=['usuario', 'fecha'], name='escuelaweb__usuario_bd8cd8_idx'), models.Index(fields=['estado'], name='escuelaweb__estado_c4509d_idx')],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]


