# Generated by Django 5.2.7 on 2026-01-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0009_asistenciapersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras para ponchar asistencia', max_length=50, null=True, unique=True),
        ),
    ]

