# Generated by Django 5.2.7 on 2026-01-15 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0011_materia_jueves_materia_lunes_materia_martes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del concepto')),
                ('tipo', models.CharField(choices=[('mensualidad', 'Mensualidad'), ('inscripcion', 'Inscripción'), ('articulo', 'Artículo/Papelería'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='mensualidad', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto base')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], max_length=20, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, help_text='Mes del año (1-12)', null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recibo_numero', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia/transacción', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('anho_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventasweb.anhoescolar')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventasweb.conceptopago')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['estudiante', 'anho_escolar'], name='escuelaweb__estudia_78ddfa_idx'), models.Index(fields=['estado'], name='escuelaweb__estado_58e2cc_idx'), models.Index(fields=['fecha_emision'], name='escuelaweb__fecha_e_69b084_idx'), models.Index(fields=['mes', 'anio'], name='escuelaweb__mes_9b5374_idx')],
            },
        ),
    ]


