# Generated by Django 6.0.1 on 2026-01-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0015_categoriaarticulo_articulo_movimientoinventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras para lector óptico', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['codigo_barras'], name='escuelaweb__codigo__415004_idx'),
        ),
    ]


