# Generated by Django 6.0.1 on 2026-01-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0017_remove_articulo_escuelaweb__codigo_74c1f8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='articulo',
            field=models.ForeignKey(blank=True, help_text='Artículo del inventario (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='ventasweb.articulo'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasweb.conceptopago'),
        ),
    ]


