# Generated by Django 6.0.1 on 2026-01-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0020_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
    ]

