# Generated by Django 6.0.1 on 2026-01-23 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0022_mensualidad_detallefactura_mensualidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='mes',
            field=models.IntegerField(help_text='Mes numérico (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='mes',
            field=models.IntegerField(blank=True, help_text='Mes del año (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]

