# Generated by Django 6.0.1 on 2026-01-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0023_alter_mensualidad_mes_alter_pago_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensualidad', 'Mensualidad'), ('inscripcion', 'Inscripción/Reinscripción')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasweb.conceptopago')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifas_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarifa Estudiante',
                'verbose_name_plural': 'Tarifas por Estudiante',
                'unique_together': {('estudiante', 'tipo')},
            },
        ),
    ]

