# Generated by Django 6.0.1 on 2026-01-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0024_tarifaestudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifaestudiante',
            options={'ordering': ['estudiante', 'concepto'], 'verbose_name': 'Tarifa Estudiante', 'verbose_name_plural': 'Tarifas por Estudiante'},
        ),
        migrations.AlterUniqueTogether(
            name='tarifaestudiante',
            unique_together={('estudiante', 'concepto')},
        ),
        migrations.AddField(
            model_name='tarifaestudiante',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Ej: Transporte zona cercana, Transporte zona lejana', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tarifaestudiante',
            name='concepto',
            field=models.ForeignKey(blank=True, help_text='Solo conceptos de tipo mensualidad, inscripción o transporte', limit_choices_to={'tipo__in': ['mensualidad', 'inscripcion', 'transporte']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasweb.conceptopago'),
        ),
        migrations.RemoveField(
            model_name='tarifaestudiante',
            name='tipo',
        ),
    ]

