# Generated by Django 6.0.1 on 2026-03-02 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0030_materia_ra_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_familia', models.CharField(db_index=True, help_text='Código único para identificar la familia (ej: FAM001, GONZALEZ2024)', max_length=50, unique=True, verbose_name='Código de Familia')),
                ('apellido_familia', models.CharField(help_text='Apellido principal o nombre de la familia', max_length=100, verbose_name='Apellido de la Familia')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('descuento_general', models.DecimalField(decimal_places=2, default=0, help_text='Descuento porcentual aplicado a todos los pagos de la familia', max_digits=5, verbose_name='Descuento General (%)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el grupo familiar está activo', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre la familia', null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias_creadas', to=settings.AUTH_USER_MODEL)),
                ('responsable_pago', models.ForeignKey(blank=True, help_text='Persona responsable de realizar los pagos (padre/madre/tutor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Pago')),
            ],
            options={
                'verbose_name': 'Grupo Familiar',
                'verbose_name_plural': 'Grupos Familiares',
                'ordering': ['apellido_familia', 'codigo_familia'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='grupo_familiar',
            field=models.ForeignKey(blank=True, help_text='Grupo familiar al que pertenece el estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='ventasweb.grupofamiliar', verbose_name='Grupo Familiar'),
        ),
        migrations.AddIndex(
            model_name='grupofamiliar',
            index=models.Index(fields=['codigo_familia'], name='escuelaweb__codigo__3cc916_idx'),
        ),
        migrations.AddIndex(
            model_name='grupofamiliar',
            index=models.Index(fields=['apellido_familia'], name='escuelaweb__apellid_42e38e_idx'),
        ),
        migrations.AddIndex(
            model_name='grupofamiliar',
            index=models.Index(fields=['activo'], name='escuelaweb__activo_bd7e6f_idx'),
        ),
    ]


