# Generated by Django 6.0.1 on 2026-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0031_grupofamiliar_customuser_grupo_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='porcentaje_mora_individual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de mora para este estudiante (solo si no está en un grupo familiar)', max_digits=5, verbose_name='Porcentaje de Mora Individual (%)'),
        ),
        migrations.AddField(
            model_name='grupofamiliar',
            name='porcentaje_mora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de recargo aplicado cuando el pago está vencido', max_digits=5, verbose_name='Porcentaje de Mora (%)'),
        ),
    ]

