# Generated by Django 6.0.1 on 2026-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0032_customuser_porcentaje_mora_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupofamiliar',
            name='dia_vencimiento',
            field=models.IntegerField(default=10, help_text='Día del mes en que vencen las mensualidades (1-31)', verbose_name='Día de Vencimiento'),
        ),
    ]

