# Generated by Django 6.0.1 on 2026-03-07 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0034_plan_cuentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(db_index=True, help_text='Número único del asiento (ej: ASI-2026-001)', max_length=20, unique=True, verbose_name='Número de Asiento')),
                ('fecha_asiento', models.DateField(db_index=True, help_text='Fecha en que se registra el asiento contable', verbose_name='Fecha del Asiento')),
                ('tipo_asiento', models.CharField(choices=[('APERTURA', 'Asiento de Apertura'), ('DIARIO', 'Asiento de Diario'), ('AJUSTE', 'Asiento de Ajuste'), ('CIERRE', 'Asiento de Cierre'), ('TRASPASO', 'Asiento de Traspaso')], default='DIARIO', help_text='Clasificación del asiento contable', max_length=15, verbose_name='Tipo de Asiento')),
                ('concepto', models.TextField(help_text='Descripción general del asiento contable', verbose_name='Concepto/Descripción')),
                ('referencia', models.CharField(blank=True, help_text='Referencia externa (número de factura, recibo, etc.)', max_length=100, null=True, verbose_name='Referencia')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado')], default='BORRADOR', help_text='Estado actual del asiento', max_length=15, verbose_name='Estado')),
                ('total_debito', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma total de los débitos', max_digits=15, verbose_name='Total Débito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma total de los créditos', max_digits=15, verbose_name='Total Crédito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_contabilizacion', models.DateTimeField(blank=True, help_text='Fecha en que se contabilizó el asiento', null=True, verbose_name='Fecha de Contabilización')),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Razón por la cual se anuló el asiento', null=True, verbose_name='Motivo de Anulación')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el asiento', null=True, verbose_name='Notas')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado Por')),
                ('contabilizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_contabilizados', to=settings.AUTH_USER_MODEL, verbose_name='Contabilizado Por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha_asiento', '-numero_asiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField(default=1, help_text='Número de línea dentro del asiento', verbose_name='Línea')),
                ('descripcion', models.CharField(help_text='Descripción específica de este movimiento', max_length=255, verbose_name='Descripción')),
                ('debito', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto del débito', max_digits=15, verbose_name='Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto del crédito', max_digits=15, verbose_name='Crédito')),
                ('centro_costo', models.CharField(blank=True, help_text='Centro de costo asociado (opcional)', max_length=50, null=True, verbose_name='Centro de Costo')),
                ('referencia_interna', models.CharField(blank=True, help_text='Referencia a otro documento (factura, recibo, etc.)', max_length=100, null=True, verbose_name='Referencia Interna')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventasweb.asientocontable', verbose_name='Asiento Contable')),
                ('cuenta', models.ForeignKey(limit_choices_to={'activo': True, 'es_detalle': True}, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_asiento', to='ventasweb.plancuentas', verbose_name='Cuenta Contable')),
                ('tercero', models.ForeignKey(blank=True, help_text='Tercero asociado (cliente/proveedor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_tercero', to=settings.AUTH_USER_MODEL, verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Detalles de Asientos',
                'ordering': ['asiento', 'linea'],
            },
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['numero_asiento'], name='escuelaweb__numero__9ac4da_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha_asiento'], name='escuelaweb__fecha_a_3e58a5_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['estado'], name='escuelaweb__estado_627479_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['tipo_asiento'], name='escuelaweb__tipo_as_8bcca7_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleasiento',
            index=models.Index(fields=['asiento', 'linea'], name='escuelaweb__asiento_8ea4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleasiento',
            index=models.Index(fields=['cuenta'], name='escuelaweb__cuenta__8e0330_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleasiento',
            unique_together={('asiento', 'linea')},
        ),
    ]


