# Generated by Django 6.0.1 on 2026-03-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0035_asientocontable_detalleasiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False, verbose_name='2FA Habilitado')),
                ('secret_key', models.CharField(blank=True, max_length=32, verbose_name='Clave secreta TOTP')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Códigos de respaldo')),
                ('fecha_habilitacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de habilitación')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Autenticación de Dos Factores',
                'verbose_name_plural': 'Autenticaciones de Dos Factores',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del intento')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent del navegador')),
                ('exitoso', models.BooleanField(default=False, verbose_name='Intento exitoso')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del intento')),
                ('razon_fallo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón del fallo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['email', 'fecha'], name='escuelaweb__email_eb082c_idx'), models.Index(fields=['ip_address', 'fecha'], name='escuelaweb__ip_addr_dcf512_idx'), models.Index(fields=['-fecha'], name='escuelaweb__fecha_7f0226_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tipo_evento', models.CharField(choices=[('LOGIN', 'Login exitoso'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login fallido'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PASSWORD_RESET', 'Reseteo de contraseña'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada'), ('ACCOUNT_UNLOCKED', 'Cuenta desbloqueada'), ('PERMISSION_DENIED', 'Permiso denegado'), ('PROFILE_UPDATE', 'Actualización de perfil'), ('SESSION_EXPIRED', 'Sesión expirada'), ('2FA_ENABLED', '2FA habilitado'), ('2FA_DISABLED', '2FA deshabilitado'), ('SUSPICIOUS_ACTIVITY', 'Actividad sospechosa'), ('DATA_EXPORT', 'Exportación de datos'), ('ADMIN_ACTION', 'Acción administrativa')], max_length=50, verbose_name='Tipo de evento')),
                ('nivel_severidad', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='Nivel de severidad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata adicional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Seguridad',
                'verbose_name_plural': 'Registros de Seguridad',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='escuelaweb__usuario_61cd56_idx'), models.Index(fields=['tipo_evento', '-fecha'], name='escuelaweb__tipo_ev_c785c6_idx'), models.Index(fields=['nivel_severidad', '-fecha'], name='escuelaweb__nivel_s_f4abd0_idx'), models.Index(fields=['-fecha'], name='escuelaweb__fecha_0d2040_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clave de sesión')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('activa', models.BooleanField(default=True, verbose_name='Sesión activa')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['usuario', '-fecha_inicio'], name='escuelaweb__usuario_698657_idx'), models.Index(fields=['session_key'], name='escuelaweb__session_a2d47d_idx'), models.Index(fields=['activa', '-fecha_inicio'], name='escuelaweb__activa_b33c9d_idx')],
            },
        ),
    ]


