# Generated by Django 6.0.1 on 2026-03-16 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0036_twofactorauth_loginattempt_securitylog_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCotejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Lista de cotejo para evaluar la participación', max_length=200, verbose_name='Nombre de la Lista')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del propósito de esta lista', null=True, verbose_name='Descripción')),
                ('tipo_evaluacion', models.CharField(choices=[('actividad', 'Actividad Específica'), ('proceso', 'Evaluación de Proceso'), ('proyecto', 'Proyecto'), ('comportamiento', 'Evaluación de Comportamiento'), ('cuaderno', 'Evaluación de Cuaderno'), ('participacion', 'Participación'), ('otro', 'Otro')], default='actividad', max_length=20, verbose_name='Tipo de Evaluación')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=10.0, help_text='Puntaje máximo que se puede obtener (usualmente 10)', max_digits=5, verbose_name='Puntaje Total')),
                ('es_plantilla', models.BooleanField(default=True, help_text='Si es True, esta lista puede ser utilizada múltiples veces', verbose_name='Es Plantilla Reutilizable')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('orden_criterios', models.CharField(choices=[('manual', 'Manual'), ('alfabetico', 'Alfabético')], default='manual', max_length=20, verbose_name='Orden de Criterios')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_cotejo_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('materia', models.ForeignKey(blank=True, help_text='Dejar en blanco si es una lista general/reutilizable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_cotejo', to='ventasweb.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Lista de Cotejo',
                'verbose_name_plural': 'Listas de Cotejo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionListaCotejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Evaluación de participación - Marzo 2026', max_length=200, verbose_name='Nombre de la Evaluación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de Evaluación')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite para Calificar')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('publicada', 'Publicada')], default='borrador', max_length=15, verbose_name='Estado')),
                ('incluir_en_promedio', models.BooleanField(default=False, help_text='Si esta evaluación debe sumarse al promedio de la materia', verbose_name='Incluir en Promedio Final')),
                ('peso_en_promedio', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje que representa en el promedio (0-100)', max_digits=5, verbose_name='Peso en Promedio (%)')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_cotejo', to='ventasweb.curso', verbose_name='Curso')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_cotejo_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_cotejo', to='ventasweb.materia', verbose_name='Materia')),
                ('lista_cotejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='ventasweb.listacotejo', verbose_name='Lista de Cotejo')),
            ],
            options={
                'verbose_name': 'Evaluación con Lista de Cotejo',
                'verbose_name_plural': 'Evaluaciones con Listas de Cotejo',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='CriterioListaCotejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Completo las actividades en clase', max_length=300, verbose_name='Descripción del Criterio')),
                ('tipo_criterio', models.CharField(choices=[('binario', 'Binario (✓/✗ - Sí/No)'), ('numerico', 'Numérico (0-10)'), ('escala_5', 'Escala 1-5'), ('escala_3', 'Escala 1-3'), ('porcentaje', 'Porcentaje (0-100%)')], default='binario', max_length=15, verbose_name='Tipo de Criterio')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=1.0, help_text='Puntos que vale este criterio', max_digits=5, verbose_name='Puntaje Máximo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista (menor número = primero)', verbose_name='Orden')),
                ('es_obligatorio', models.BooleanField(default=True, help_text='Si debe ser evaluado obligatoriamente', verbose_name='Es Obligatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('lista_cotejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='ventasweb.listacotejo', verbose_name='Lista de Cotejo')),
            ],
            options={
                'verbose_name': 'Criterio de Lista de Cotejo',
                'verbose_name_plural': 'Criterios de Listas de Cotejo',
                'ordering': ['orden', 'id'],
                'unique_together': {('lista_cotejo', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionCotejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor según el tipo de criterio', max_digits=6, null=True, verbose_name='Valor Obtenido')),
                ('cumple', models.BooleanField(blank=True, null=True, verbose_name='Cumple (Para criterios binarios)')),
                ('observacion', models.TextField(blank=True, help_text='Comentario específico sobre este criterio para este estudiante', null=True, verbose_name='Observación')),
                ('fecha_calificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Calificación')),
                ('calificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_cotejo_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Calificado Por')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_cotejo', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='ventasweb.criteriolistacotejo', verbose_name='Criterio')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='ventasweb.evaluacionlistacotejo', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Calificación de Cotejo',
                'verbose_name_plural': 'Calificaciones de Cotejo',
                'ordering': ['estudiante', 'criterio__orden'],
                'unique_together': {('evaluacion', 'estudiante', 'criterio')},
            },
        ),
        migrations.CreateModel(
            name='ResumenEvaluacionCotejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje Obtenido')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Puntaje Máximo')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje (%)')),
                ('criterios_evaluados', models.PositiveIntegerField(default=0, verbose_name='Criterios Evaluados')),
                ('criterios_totales', models.PositiveIntegerField(default=0, verbose_name='Criterios Totales')),
                ('esta_completo', models.BooleanField(default=False, verbose_name='Evaluación Completa')),
                ('fecha_calculo', models.DateTimeField(auto_now=True, verbose_name='Fecha de Cálculo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_cotejo', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='ventasweb.evaluacionlistacotejo', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Resumen de Evaluación de Cotejo',
                'verbose_name_plural': 'Resúmenes de Evaluaciones de Cotejo',
                'ordering': ['estudiante__first_name', 'estudiante__last_name'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
    ]

