# Generated by Django 6.0.1 on 2026-03-24 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0038_tarifaestudiante_dia_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dia_vencimiento_individual',
            field=models.IntegerField(default=10, help_text='Día del mes para vencimiento de pago (solo si no está en un grupo familiar)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de Vencimiento Individual'),
        ),
    ]

