# Generated by Django 6.0.1 on 2026-03-28 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0042_evaluaciondiagnostica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoEvaluacionDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_logro', models.CharField(choices=[('no_alcanzado', 'No Alcanzado'), ('en_proceso', 'En Proceso'), ('alcanzado', 'Alcanzado'), ('supera', 'Supera lo Esperado')], max_length=20, verbose_name='Nivel de Logro')),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje numérico obtenido (opcional)', max_digits=5, null=True, verbose_name='Puntaje Obtenido')),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje total de la evaluación (opcional)', max_digits=5, null=True, verbose_name='Puntaje Total')),
                ('fortalezas', models.TextField(blank=True, help_text='Aspectos en los que el estudiante demuestra dominio', null=True, verbose_name='Fortalezas Identificadas')),
                ('debilidades', models.TextField(blank=True, help_text='Aspectos que requieren refuerzo o intervención', null=True, verbose_name='Áreas de Mejora')),
                ('recomendaciones', models.TextField(blank=True, help_text='Estrategias pedagógicas sugeridas para este estudiante', null=True, verbose_name='Recomendaciones')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_diagnosticas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='ventasweb.evaluaciondiagnostica', verbose_name='Evaluación Diagnóstica')),
                ('evaluado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_diagnosticas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado Por')),
            ],
            options={
                'verbose_name': 'Resultado de Evaluación Diagnóstica',
                'verbose_name_plural': 'Resultados de Evaluaciones Diagnósticas',
                'ordering': ['estudiante__first_name', 'estudiante__last_name'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
    ]

