# Generated by Django 6.0.1 on 2026-03-28 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0043_resultadoevaluaciondiagnostica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Evaluación de Proyecto de Ciencias', max_length=255, verbose_name='Nombre de la Rúbrica')),
                ('tipo_actividad', models.CharField(choices=[('proyecto', 'Proyecto'), ('presentacion', 'Presentación Oral'), ('trabajo_escrito', 'Trabajo Escrito'), ('trabajo_grupo', 'Trabajo en Grupo'), ('experimentacion', 'Experimentación/Práctica'), ('exposicion', 'Exposición'), ('debate', 'Debate'), ('otro', 'Otro')], default='proyecto', max_length=20, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general de la rúbrica', null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la rúbrica está activa para usar', verbose_name='Activa')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='ventasweb.materia', verbose_name='Materia/Asignatura')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CriterioRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Contenido y Profundidad, Organización, Presentación Visual', max_length=255, verbose_name='Nombre del Criterio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de qué se evaluará en este criterio', null=True, verbose_name='Descripción')),
                ('ponderacion', models.DecimalField(decimal_places=2, default=20.0, help_text='Peso del criterio en la evaluación final (ej: 20.00%)', max_digits=5, verbose_name='Ponderación (%)')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización del criterio', verbose_name='Orden')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='ventasweb.rubrica', verbose_name='Rúbrica')),
            ],
            options={
                'verbose_name': 'Criterio de Rúbrica',
                'verbose_name_plural': 'Criterios de Rúbrica',
                'ordering': ['rubrica', 'orden', 'id'],
                'unique_together': {('rubrica', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='NivelDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('excelente', 'Excelente (5)'), ('muy_bueno', 'Muy Bueno (4)'), ('bueno', 'Bueno (3)'), ('regular', 'Regular (2)'), ('necesita_mejorar', 'Necesita Mejorar (1)')], max_length=20, verbose_name='Nivel de Desempeño')),
                ('puntaje', models.DecimalField(decimal_places=2, help_text='Puntaje numérico para este nivel (1-5)', max_digits=5, verbose_name='Puntaje')),
                ('descriptor', models.TextField(help_text='Descripción detallada de lo que caracteriza este nivel de desempeño', verbose_name='Descriptor')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='ventasweb.criteriorubrica', verbose_name='Criterio')),
            ],
            options={
                'verbose_name': 'Nivel de Desempeño',
                'verbose_name_plural': 'Niveles de Desempeño',
                'ordering': ['-puntaje'],
                'unique_together': {('criterio', 'nivel')},
            },
        ),
    ]

