# Generated by Django 6.0.1 on 2026-03-28 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0044_rubrica_criteriorubrica_niveldesempeno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre descriptivo de la evaluación (ej: Proyecto Final, Exposición Oral)', max_length=200, verbose_name='Título de la Evaluación')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles de la actividad evaluada', null=True, verbose_name='Descripción')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de Evaluación')),
                ('periodo', models.CharField(help_text='Ej: Primer Período, Segundo Período', max_length=50, verbose_name='Período')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_rubrica_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada Por')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_rubrica', to='ventasweb.curso', verbose_name='Curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_rubrica', to='ventasweb.materia', verbose_name='Materia')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='ventasweb.rubrica', verbose_name='Rúbrica')),
            ],
            options={
                'verbose_name': 'Evaluación con Rúbrica',
                'verbose_name_plural': 'Evaluaciones con Rúbrica',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios específicos sobre el desempeño en este criterio', null=True, verbose_name='Observaciones')),
                ('fecha_calificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Calificación')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='ventasweb.criteriorubrica', verbose_name='Criterio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_rubrica', to='ventasweb.estudiante', verbose_name='Estudiante')),
                ('nivel_otorgado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='ventasweb.niveldesempeno', verbose_name='Nivel Otorgado')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='ventasweb.evaluacionrubrica', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Calificación de Criterio',
                'verbose_name_plural': 'Calificaciones de Criterios',
                'ordering': ['criterio__orden'],
                'unique_together': {('evaluacion', 'estudiante', 'criterio')},
            },
        ),
    ]

