# Generated by Django 6.0.1 on 2026-03-28 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0045_evaluacionrubrica_calificacioncriterio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacioncriterio',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_rubrica', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
    ]

