# Generated by Django 6.0.1 on 2026-04-06 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0047_configuracionescuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='Dirección IP')),
                ('tipo_bloqueo', models.CharField(choices=[('MANUAL', 'Bloqueo Manual'), ('AUTO_RATE_LIMIT', 'Automático - Rate Limit'), ('AUTO_FAILED_LOGIN', 'Automático - Login Fallido'), ('AUTO_SUSPICIOUS', 'Automático - Actividad Sospechosa')], default='MANUAL', max_length=30, verbose_name='Tipo de Bloqueo')),
                ('razon', models.TextField(verbose_name='Razón del Bloqueo')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Bloqueo')),
                ('es_temporal', models.BooleanField(default=False, verbose_name='Bloqueo Temporal')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('activo', models.BooleanField(default=True, verbose_name='Bloqueo Activo')),
                ('intentos_durante_bloqueo', models.IntegerField(default=0, verbose_name='Intentos Durante Bloqueo')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País de Origen')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata Adicional')),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_bloqueadas', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado Por')),
            ],
            options={
                'verbose_name': 'IP Bloqueada',
                'verbose_name_plural': 'IPs Bloqueadas',
                'ordering': ['-fecha_bloqueo'],
                'indexes': [models.Index(fields=['ip_address'], name='escuelaweb__ip_addr_12cd6f_idx'), models.Index(fields=['activo', '-fecha_bloqueo'], name='escuelaweb__activo_2bbed6_idx'), models.Index(fields=['es_temporal', 'fecha_expiracion'], name='escuelaweb__es_temp_9e1234_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('BRUTE_FORCE', 'Intento de Fuerza Bruta'), ('MULTIPLE_FAILED_LOGIN', 'Múltiples Intentos Fallidos'), ('SUSPICIOUS_IP', 'IP Sospechosa'), ('UNUSUAL_LOCATION', 'Ubicación Inusual'), ('UNUSUAL_TIME', 'Hora Inusual'), ('ACCOUNT_COMPROMISE', 'Posible Cuenta Comprometida'), ('DATA_BREACH', 'Posible Filtración de Datos'), ('PRIVILEGE_ESCALATION', 'Escalada de Privilegios'), ('UNAUTHORIZED_ACCESS', 'Acceso No Autorizado'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de Alerta')),
                ('nivel_prioridad', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISANDO', 'En Revisión'), ('RESUELTA', 'Resuelta'), ('FALSA_ALARMA', 'Falsa Alarma'), ('IGNORADA', 'Ignorada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alerta')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('acciones_tomadas', models.TextField(blank=True, verbose_name='Acciones Tomadas')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('fecha_email', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Email')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata Adicional')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto Por')),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_seguridad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Afectado')),
            ],
            options={
                'verbose_name': 'Alerta de Seguridad',
                'verbose_name_plural': 'Alertas de Seguridad',
                'ordering': ['-fecha_alerta'],
                'indexes': [models.Index(fields=['estado', '-fecha_alerta'], name='escuelaweb__estado_f2acf0_idx'), models.Index(fields=['nivel_prioridad', '-fecha_alerta'], name='escuelaweb__nivel_p_3fb09c_idx'), models.Index(fields=['usuario_afectado', '-fecha_alerta'], name='escuelaweb__usuario_740ba0_idx'), models.Index(fields=['asignado_a', '-fecha_alerta'], name='escuelaweb__asignad_b39dc9_idx')],
            },
        ),
    ]


