# Generated by Django 6.0.1 on 2026-04-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0048_ipblocklist_securityalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(help_text='ID del terminal POS', max_length=50, unique=True)),
                ('proveedor', models.CharField(choices=[('cardnet', 'Cardnet'), ('azul', 'Azul'), ('otro', 'Otro')], default='cardnet', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, los pagos en este terminal se asociarán automáticamente al estudiante')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='terminales_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terminal-Estudiante',
                'verbose_name_plural': 'Terminales-Estudiantes',
                'ordering': ['terminal_id'],
                'indexes': [models.Index(fields=['terminal_id', 'activo'], name='escuelaweb__termina_c3fec8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='ID único de la transacción en el proveedor', max_length=100, unique=True)),
                ('proveedor', models.CharField(choices=[('cardnet', 'Cardnet'), ('azul', 'Azul'), ('otro', 'Otro')], default='cardnet', max_length=20)),
                ('terminal_id', models.CharField(help_text='ID del terminal POS que procesó el pago', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total de la transacción', max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia de la transacción', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('procesado', 'Procesado'), ('pendiente_revision', 'Pendiente de Revisión'), ('sin_factura', 'Sin Factura Asociada'), ('error', 'Error'), ('rechazado', 'Rechazado')], default='procesado', max_length=30)),
                ('tarjeta_ultimos_4', models.CharField(blank=True, max_length=4, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20, null=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se recibió la notificación')),
                ('fecha_procesamiento', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('datos_webhook', models.JSONField(blank=True, help_text='Datos completos recibidos del webhook', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(blank=True, limit_choices_to={'rol': 'Estudiante'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_pos', to=settings.AUTH_USER_MODEL)),
                ('factura_pagada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_pos', to='ventasweb.factura')),
            ],
            options={
                'verbose_name': 'Transacción POS',
                'verbose_name_plural': 'Transacciones POS',
                'ordering': ['-fecha_transaccion'],
                'indexes': [models.Index(fields=['transaction_id'], name='escuelaweb__transac_dab7b6_idx'), models.Index(fields=['proveedor', 'terminal_id'], name='escuelaweb__proveed_6196a7_idx'), models.Index(fields=['estudiante', 'fecha_transaccion'], name='escuelaweb__estudia_36b328_idx'), models.Index(fields=['estado'], name='escuelaweb__estado_4e1940_idx')],
            },
        ),
    ]


