# Generated by Django 6.0.1 on 2026-04-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0049_terminalestudiante_transaccionpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cie_rp1',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie RP1'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cie_rp2',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie RP2'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cie_rp3',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie RP3'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cie_rp4',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie RP4'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='com_rp1',
            field=models.FloatField(blank=True, null=True, verbose_name='Com RP1'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='com_rp2',
            field=models.FloatField(blank=True, null=True, verbose_name='Com RP2'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='com_rp3',
            field=models.FloatField(blank=True, null=True, verbose_name='Com RP3'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='com_rp4',
            field=models.FloatField(blank=True, null=True, verbose_name='Com RP4'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='eti_rp1',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti RP1'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='eti_rp2',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti RP2'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='eti_rp3',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti RP3'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='eti_rp4',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti RP4'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='log_rp1',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat RP1'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='log_rp2',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat RP2'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='log_rp3',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat RP3'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='log_rp4',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat RP4'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cie_p1',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie P1'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cie_p2',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie P2'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cie_p3',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie P3'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cie_p4',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie P4'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cie_rp',
            field=models.FloatField(blank=True, null=True, verbose_name='Cie RP Final'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='com_p1',
            field=models.FloatField(blank=True, null=True, verbose_name='Com P1'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='com_p2',
            field=models.FloatField(blank=True, null=True, verbose_name='Com P2'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='com_p3',
            field=models.FloatField(blank=True, null=True, verbose_name='Com P3'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='com_p4',
            field=models.FloatField(blank=True, null=True, verbose_name='Com P4'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='com_rp',
            field=models.FloatField(blank=True, null=True, verbose_name='Com RP Final'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='eti_p1',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti P1'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='eti_p2',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti P2'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='eti_p3',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti P3'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='eti_p4',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti P4'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='eti_rp',
            field=models.FloatField(blank=True, null=True, verbose_name='Eti RP Final'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='log_p1',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat P1'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='log_p2',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat P2'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='log_p3',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat P3'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='log_p4',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat P4'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='log_rp',
            field=models.FloatField(blank=True, null=True, verbose_name='Mat RP Final'),
        ),
    ]

