# Generated by Django 6.0.1 on 2026-05-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0052_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='anhoescolar',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anhos_escolares', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_pago', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='curso',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='escuela',
            field=models.ForeignKey(blank=True, help_text='Escuela/Colegio al que pertenece este usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_modelo', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='factura',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='grupofamiliar',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_familiares', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='materia',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='pago',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesores_modelo', to='ventasweb.escuela', verbose_name='Escuela'),
        ),
    ]

