# Generated by Django 5.1.4 on 2026-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0058_remove_anhoescolar_escuela_remove_articulo_escuela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activation_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='Token de Activación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]

