# Generated by Django 5.1.4 on 2026-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0059_client_activation_token_alter_client_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEscuelaAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('nombre_corto_intentado', models.CharField(blank=True, max_length=50, verbose_name='Subdominio Intentado')),
                ('exitoso', models.BooleanField(default=False, verbose_name='Registro Exitoso')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Intento')),
                ('razon_fallo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón del Fallo')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Intento de Registro de Escuela',
                'verbose_name_plural': 'Intentos de Registro de Escuelas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['ip_address', 'fecha'], name='escuelaweb__ip_addr_d76c3d_idx'), models.Index(fields=['-fecha'], name='escuelaweb__fecha_98c5e4_idx')],
            },
        ),
    ]


