# Generated by Django 4.2.17 on 2026-05-30 03:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0061_historialpago_plan_suscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(db_index=True, help_text='Código único para identificar el cliente corporativo (ej: CORP001, EMPRESA2024)', max_length=50, unique=True, verbose_name='Código de Cliente')),
                ('nombre_empresa', models.CharField(help_text='Razón social o nombre comercial', max_length=200, verbose_name='Nombre de la Empresa')),
                ('rnc', models.CharField(blank=True, help_text='Registro Nacional de Contribuyentes', max_length=20, null=True, unique=True, verbose_name='RNC')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('descuento_general', models.DecimalField(decimal_places=2, default=0, help_text='Descuento porcentual aplicado a todas las compras', max_digits=5, verbose_name='Descuento General (%)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, help_text='Límite de crédito corporativo', max_digits=12, verbose_name='Límite de Crédito')),
                ('dias_credito', models.IntegerField(default=30, help_text='Cantidad de días de crédito otorgado', verbose_name='Días de Crédito')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente corporativo está activo', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre el cliente', null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente Corporativo',
                'verbose_name_plural': 'Clientes Corporativos',
                'ordering': ['nombre_empresa', 'codigo_cliente'],
            },
        ),
        migrations.CreateModel(
            name='ComisionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comisión de Vendedor',
                'verbose_name_plural': 'Comisiones de Vendedores',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_cotizacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('valida_hasta', models.DateField(help_text='Fecha hasta la cual es válida la cotización')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida a Factura'), ('vencida', 'Vencida')], db_index=True, default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.IntegerField()),
                ('meta_monto', models.DecimalField(decimal_places=2, help_text='Meta de ventas en dinero para el mes', max_digits=12, verbose_name='Meta en Monto')),
                ('meta_cantidad', models.IntegerField(default=0, help_text='Meta de cantidad de facturas/ventas', verbose_name='Meta en Cantidad')),
                ('monto_alcanzado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Alcanzado')),
                ('cantidad_alcanzada', models.IntegerField(default=0, verbose_name='Cantidad Alcanzada')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta de Vendedor',
                'verbose_name_plural': 'Metas de Vendedores',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.RenameIndex(
            model_name='articulo',
            new_name='ventasweb_a_codigo__c0a603_idx',
            old_name='escuelaweb__codigo__415004_idx',
        ),
        migrations.RenameIndex(
            model_name='articulo',
            new_name='ventasweb_a_nombre_3c2f7e_idx',
            old_name='escuelaweb__nombre_e385a9_idx',
        ),
        migrations.RenameIndex(
            model_name='articulo',
            new_name='ventasweb_a_activo_d7e5c9_idx',
            old_name='escuelaweb__activo_a4edcd_idx',
        ),
        migrations.RenameIndex(
            model_name='asientocontable',
            new_name='ventasweb_a_numero__3ce207_idx',
            old_name='escuelaweb__numero__9ac4da_idx',
        ),
        migrations.RenameIndex(
            model_name='asientocontable',
            new_name='ventasweb_a_fecha_a_6bc924_idx',
            old_name='escuelaweb__fecha_a_3e58a5_idx',
        ),
        migrations.RenameIndex(
            model_name='asientocontable',
            new_name='ventasweb_a_estado_b09072_idx',
            old_name='escuelaweb__estado_627479_idx',
        ),
        migrations.RenameIndex(
            model_name='asientocontable',
            new_name='ventasweb_a_tipo_as_cfbdc2_idx',
            old_name='escuelaweb__tipo_as_8bcca7_idx',
        ),
        migrations.RenameIndex(
            model_name='asistencia',
            new_name='ventasweb_a_fecha_f7516e_idx',
            old_name='escuelaweb__fecha_0abf41_idx',
        ),
        migrations.RenameIndex(
            model_name='asistencia',
            new_name='ventasweb_a_estudia_3cf748_idx',
            old_name='escuelaweb__estudia_36dab8_idx',
        ),
        migrations.RenameIndex(
            model_name='asistenciapersonal',
            new_name='ventasweb_a_fecha_834acb_idx',
            old_name='escuelaweb__fecha_ec4ae2_idx',
        ),
        migrations.RenameIndex(
            model_name='asistenciapersonal',
            new_name='ventasweb_a_usuario_5be38b_idx',
            old_name='escuelaweb__usuario_bd8cd8_idx',
        ),
        migrations.RenameIndex(
            model_name='asistenciapersonal',
            new_name='ventasweb_a_estado_3c1ea1_idx',
            old_name='escuelaweb__estado_c4509d_idx',
        ),
        migrations.RenameIndex(
            model_name='detalleasiento',
            new_name='ventasweb_d_asiento_e41c68_idx',
            old_name='escuelaweb__asiento_8ea4ad_idx',
        ),
        migrations.RenameIndex(
            model_name='detalleasiento',
            new_name='ventasweb_d_cuenta__cc9083_idx',
            old_name='escuelaweb__cuenta__8e0330_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventasweb_f_numero__0f676e_idx',
            old_name='escuelaweb__numero__b9f71d_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventasweb_f_cliente_a61b0b_idx',
            old_name='escuelaweb__cliente_e150d0_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventasweb_f_estado_ec968a_idx',
            old_name='escuelaweb__estado_17c6bd_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='ventasweb_f_fecha_e_9df5ed_idx',
            old_name='escuelaweb__fecha_e_5ae072_idx',
        ),
        migrations.RenameIndex(
            model_name='grupofamiliar',
            new_name='ventasweb_g_codigo__9a31f6_idx',
            old_name='escuelaweb__codigo__3cc916_idx',
        ),
        migrations.RenameIndex(
            model_name='grupofamiliar',
            new_name='ventasweb_g_apellid_98b040_idx',
            old_name='escuelaweb__apellid_42e38e_idx',
        ),
        migrations.RenameIndex(
            model_name='grupofamiliar',
            new_name='ventasweb_g_activo_c5e853_idx',
            old_name='escuelaweb__activo_bd7e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='historialpago',
            new_name='ventasweb_h_suscrip_b8f8ea_idx',
            old_name='escuelaweb__suscrip_49ac34_idx',
        ),
        migrations.RenameIndex(
            model_name='historialpago',
            new_name='ventasweb_h_estado_6329e0_idx',
            old_name='escuelaweb__estado_8b4590_idx',
        ),
        migrations.RenameIndex(
            model_name='historialpago',
            new_name='ventasweb_h_stripe__6bc19e_idx',
            old_name='escuelaweb__stripe__efc9c1_idx',
        ),
        migrations.RenameIndex(
            model_name='ipblocklist',
            new_name='ventasweb_i_ip_addr_4d0a60_idx',
            old_name='escuelaweb__ip_addr_12cd6f_idx',
        ),
        migrations.RenameIndex(
            model_name='ipblocklist',
            new_name='ventasweb_i_activo_17e0b6_idx',
            old_name='escuelaweb__activo_2bbed6_idx',
        ),
        migrations.RenameIndex(
            model_name='ipblocklist',
            new_name='ventasweb_i_es_temp_087035_idx',
            old_name='escuelaweb__es_temp_9e1234_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='ventasweb_l_email_44894f_idx',
            old_name='escuelaweb__email_eb082c_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='ventasweb_l_ip_addr_d165ca_idx',
            old_name='escuelaweb__ip_addr_dcf512_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='ventasweb_l_fecha_d22522_idx',
            old_name='escuelaweb__fecha_7f0226_idx',
        ),
        migrations.RenameIndex(
            model_name='matricula',
            new_name='ventasweb_m_estudia_7c3fc9_idx',
            old_name='escuelaweb__estudia_f27026_idx',
        ),
        migrations.RenameIndex(
            model_name='matricula',
            new_name='ventasweb_m_materia_9d30a0_idx',
            old_name='escuelaweb__materia_8952b1_idx',
        ),
        migrations.RenameIndex(
            model_name='matricula',
            new_name='ventasweb_m_anho_es_56ee4d_idx',
            old_name='escuelaweb__anho_es_74454c_idx',
        ),
        migrations.RenameIndex(
            model_name='pago',
            new_name='ventasweb_p_estudia_6fe7a3_idx',
            old_name='escuelaweb__estudia_78ddfa_idx',
        ),
        migrations.RenameIndex(
            model_name='pago',
            new_name='ventasweb_p_estado_621199_idx',
            old_name='escuelaweb__estado_58e2cc_idx',
        ),
        migrations.RenameIndex(
            model_name='pago',
            new_name='ventasweb_p_fecha_e_3dc0f5_idx',
            old_name='escuelaweb__fecha_e_69b084_idx',
        ),
        migrations.RenameIndex(
            model_name='pago',
            new_name='ventasweb_p_mes_7f923d_idx',
            old_name='escuelaweb__mes_9b5374_idx',
        ),
        migrations.RenameIndex(
            model_name='pagofactura',
            new_name='ventasweb_p_factura_29c7a6_idx',
            old_name='escuelaweb__factura_d5bb81_idx',
        ),
        migrations.RenameIndex(
            model_name='pagofactura',
            new_name='ventasweb_p_metodo__b009d1_idx',
            old_name='escuelaweb__metodo__73c62d_idx',
        ),
        migrations.RenameIndex(
            model_name='plancuentas',
            new_name='ventasweb_p_codigo_fa3904_idx',
            old_name='escuelaweb__codigo_f90559_idx',
        ),
        migrations.RenameIndex(
            model_name='plancuentas',
            new_name='ventasweb_p_tipo_cu_d59f03_idx',
            old_name='escuelaweb__tipo_cu_fd24c3_idx',
        ),
        migrations.RenameIndex(
            model_name='plancuentas',
            new_name='ventasweb_p_activo_537baa_idx',
            old_name='escuelaweb__activo_c0e861_idx',
        ),
        migrations.RenameIndex(
            model_name='plancuentas',
            new_name='ventasweb_p_es_deta_7a9942_idx',
            old_name='escuelaweb__es_deta_98ebfb_idx',
        ),
        migrations.RenameIndex(
            model_name='registroescuelaattempt',
            new_name='ventasweb_r_ip_addr_fa9636_idx',
            old_name='escuelaweb__ip_addr_d76c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='registroescuelaattempt',
            new_name='ventasweb_r_fecha_f46515_idx',
            old_name='escuelaweb__fecha_98c5e4_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='ventasweb_s_estado_ef01be_idx',
            old_name='escuelaweb__estado_f2acf0_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='ventasweb_s_nivel_p_e1b6d6_idx',
            old_name='escuelaweb__nivel_p_3fb09c_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='ventasweb_s_usuario_7b6bba_idx',
            old_name='escuelaweb__usuario_740ba0_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='ventasweb_s_asignad_5a8908_idx',
            old_name='escuelaweb__asignad_b39dc9_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='ventasweb_s_usuario_2706ce_idx',
            old_name='escuelaweb__usuario_61cd56_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='ventasweb_s_tipo_ev_07f336_idx',
            old_name='escuelaweb__tipo_ev_c785c6_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='ventasweb_s_nivel_s_3b1df0_idx',
            old_name='escuelaweb__nivel_s_f4abd0_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='ventasweb_s_fecha_2076af_idx',
            old_name='escuelaweb__fecha_0d2040_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='ventasweb_u_usuario_ffc6cc_idx',
            old_name='escuelaweb__usuario_698657_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='ventasweb_u_session_45e3b2_idx',
            old_name='escuelaweb__session_a2d47d_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='ventasweb_u_activa_3edbf6_idx',
            old_name='escuelaweb__activa_b33c9d_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='descuento_individual',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dia_vencimiento_individual',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grupo_familiar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='porcentaje_mora_individual',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='seccion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='comision_vendedor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión sobre las ventas', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión Vendedor (%)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='descuento_cliente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento general para el cliente', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Cliente (%)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dias_credito',
            field=models.IntegerField(default=30, help_text='Cantidad de días de crédito otorgado al cliente', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Días de Crédito'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo de crédito disponible para el cliente', max_digits=12, verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='meta_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Meta de ventas mensual para el vendedor', max_digits=12, verbose_name='Meta Mensual'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('individual', 'Cliente Individual'), ('corporativo', 'Cliente Corporativo')], help_text='Tipo de cliente: individual o corporativo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zona_venta',
            field=models.CharField(blank=True, help_text='Zona geográfica asignada al vendedor', max_length=100, null=True, verbose_name='Zona de Venta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'Vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Moroso', 'Moroso'), ('Bloqueado', 'Bloqueado')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Gerente', 'Gerente'), ('Secretaria', 'Secretaria'), ('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Almacenista', 'Almacenista'), ('Asistente', 'Asistente'), ('Otro', 'Otro')], default='Cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='anho_escolar',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Solo para compatibilidad con datos antiguos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='ventasweb.anhoescolar'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'Cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque'), ('mixto', 'Mixto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el grupo familiar está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='codigo_familia',
            field=models.CharField(db_index=True, help_text='Código único para identificar la familia (ej: FAM001, GONZALEZ2024)', max_length=50, unique=True, verbose_name='Código de Familia'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='dia_vencimiento',
            field=models.IntegerField(default=10, help_text='Día del mes en que vencen las mensualidades (1-31)', verbose_name='Día de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='notas',
            field=models.TextField(blank=True, help_text='Información adicional sobre la familia', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='porcentaje_mora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de recargo aplicado cuando el pago está vencido', max_digits=5, verbose_name='Porcentaje de Mora (%)'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='metavendedor',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'rol': 'Vendedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='ventasweb.articulo'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventasweb.cotizacion'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='factura_generada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ventasweb.factura'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'rol': 'Vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comisionvendedor',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comisionvendedor',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventasweb.factura'),
        ),
        migrations.AddField(
            model_name='comisionvendedor',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'rol': 'Vendedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientecorporativo',
            name='contacto_principal',
            field=models.ForeignKey(blank=True, help_text='Persona responsable de contacto y pagos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_contacto', to=settings.AUTH_USER_MODEL, verbose_name='Contacto Principal'),
        ),
        migrations.AddField(
            model_name='clientecorporativo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_corporativos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cliente_corporativo',
            field=models.ForeignKey(blank=True, help_text='Empresa o grupo corporativo al que pertenece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='ventasweb.clientecorporativo', verbose_name='Cliente Corporativo'),
        ),
        migrations.AddIndex(
            model_name='metavendedor',
            index=models.Index(fields=['vendedor', 'anio', 'mes'], name='ventasweb_m_vendedo_dfc9a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metavendedor',
            unique_together={('vendedor', 'mes', 'anio')},
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_cotizacion'], name='ventasweb_c_numero__1088fd_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente', 'estado'], name='ventasweb_c_cliente_4cc703_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['vendedor', 'fecha_cotizacion'], name='ventasweb_c_vendedo_458303_idx'),
        ),
        migrations.AddIndex(
            model_name='comisionvendedor',
            index=models.Index(fields=['vendedor', 'estado'], name='ventasweb_c_vendedo_3ebcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='comisionvendedor',
            index=models.Index(fields=['factura'], name='ventasweb_c_factura_cec504_idx'),
        ),
        migrations.AddIndex(
            model_name='clientecorporativo',
            index=models.Index(fields=['codigo_cliente'], name='ventasweb_c_codigo__cb55ec_idx'),
        ),
        migrations.AddIndex(
            model_name='clientecorporativo',
            index=models.Index(fields=['nombre_empresa'], name='ventasweb_c_nombre__9a9419_idx'),
        ),
        migrations.AddIndex(
            model_name='clientecorporativo',
            index=models.Index(fields=['rnc'], name='ventasweb_c_rnc_168574_idx'),
        ),
        migrations.AddIndex(
            model_name='clientecorporativo',
            index=models.Index(fields=['activo'], name='ventasweb_c_activo_32a6b1_idx'),
        ),
    ]
