# Generated by Django 5.1.4 on 2026-06-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0062_clientecorporativo_comisionvendedor_cotizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('Minorista', 'Minorista'), ('Mayorista', 'Mayorista'), ('Corporativo', 'Corporativo')], help_text='Tipo de cliente: Minorista, Mayorista o Corporativo', max_length=20, null=True),
        ),
    ]
