# Generated by Django 5.1.4 on 2026-08-20 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0063_alter_customuser_tipo_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['nombre'], 'verbose_name': 'ArtÃ\xadculo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='categoriaarticulo',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de ArtÃ\xadculo', 'verbose_name_plural': 'Categorías de Artículos'},
        ),
        migrations.AlterField(
            model_name='configuracionescuela',
            name='pie_pagina_reportes',
            field=models.TextField(blank=True, help_text='Texto que aparecera¡ al pie de los reportes oficiales', null=True, verbose_name='Pie de PÃ¡gina para Reportes'),
        ),
        migrations.AlterField(
            model_name='evaluaciondiagnostica',
            name='periodo',
            field=models.CharField(choices=[('inicio_anho', 'Inicio de Año Escolar'), ('inicio_periodo_1', 'Inicio Primer Período'), ('inicio_periodo_2', 'Inicio Segundo Período'), ('inicio_periodo_3', 'Inicio Tercer Período'), ('inicio_periodo_4', 'Inicio Cuarto Período'), ('inicio_unidad', 'Inicio de Unidad DidÃ¡ctica')], max_length=20, verbose_name='Período de AplicaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='periodo',
            field=models.CharField(help_text='Ej: Primer Período, Segundo Período', max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='evaluacionrubrica',
            name='titulo',
            field=models.CharField(help_text='Nombre descriptivo de la evaluación (ej: Proyecto Final, ExposiciÃ³n Oral)', max_length=200, verbose_name='Título de la Evaluación'),
        ),
        migrations.AlterField(
            model_name='ipblocklist',
            name='tipo_bloqueo',
            field=models.CharField(choices=[('MANUAL', 'Bloqueo Manual'), ('AUTO_RATE_LIMIT', 'Automatico - Rate Limit'), ('AUTO_FAILED_LOGIN', 'Automatico - Login Fallido'), ('AUTO_SUSPICIOUS', 'Automatico - Actividad Sospechosa')], default='MANUAL', max_length=30, verbose_name='Tipo de Bloqueo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='categoria',
            field=models.CharField(choices=[('periodo', 'Por Períodos'), ('modular', 'Modular')], default='periodo', help_text='Por Períodos: calificaciones por período (P1, P2, P3). Modular: evaluación continua.', max_length=20, verbose_name='Categoría de Evaluación'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo inicial de la cuenta al inicio del período contable', max_digits=15, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tarifaestudiante',
            name='dia_vencimiento',
            field=models.IntegerField(blank=True, default=None, help_text='Día del mes para vencimiento de pago (1-31). Si no se especifica, usa el del grupo familiar.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
