# Generated by Django 4.2.17 on 2026-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0064_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facturacion_electronica',
            field=models.BooleanField(default=False, verbose_name='Facturación Electrónica'),
        ),
        migrations.AddField(
            model_name='client',
            name='facturas_mes_actual',
            field=models.IntegerField(default=0, verbose_name='Facturas este mes'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_facturas_mes',
            field=models.IntegerField(default=50, verbose_name='Máximo Facturas/Mes'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_sucursales',
            field=models.IntegerField(default=1, verbose_name='Máximo de Sucursales'),
        ),
        migrations.AddField(
            model_name='client',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mensual (USD)'),
        ),
        migrations.AddField(
            model_name='client',
            name='proximo_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Pago'),
        ),
        migrations.AddField(
            model_name='client',
            name='reportes_avanzados',
            field=models.BooleanField(default=False, verbose_name='Reportes Avanzados'),
        ),
        migrations.AddField(
            model_name='client',
            name='ultimo_reset_facturas',
            field=models.DateField(blank=True, null=True, verbose_name='Último reset de facturas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_usuarios',
            field=models.IntegerField(default=1, verbose_name='Máximo de Usuarios'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_corto',
            field=models.CharField(help_text='Se usará como subdominio: nombre-corto.misventasflash.com', max_length=50, unique=True, verbose_name='Nombre Corto (Subdominio)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('gratis', 'Gratis (30 días)'), ('basico', 'Básico - $5/mes'), ('plus', 'Plus - $12/mes'), ('pro', 'Pro - $25/mes')], default='gratis', max_length=20, verbose_name='Plan de Suscripción'),
        ),
    ]
