# Generated by Django 4.2.17 on 2026-08-29 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0065_client_facturacion_electronica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotización'},
        ),
        migrations.RemoveIndex(
            model_name='cotizacion',
            name='ventasweb_c_cliente_4cc703_idx',
        ),
        migrations.RemoveIndex(
            model_name='cotizacion',
            name='ventasweb_c_vendedo_458303_idx',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='condiciones_pago',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='itbis',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='valida_hasta',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas solo para uso interno', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas para el cliente', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='terminos_condiciones',
            field=models.TextField(blank=True, help_text='Términos y condiciones de la cotización', null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'Cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al Cliente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida a Factura'), ('vencida', 'Vencida')], db_index=True, default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateField(help_text='Fecha hasta la cual es válida la cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'Vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='articulo',
            field=models.ForeignKey(blank=True, help_text='Artículo del inventario (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='ventasweb.articulo'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='descripcion',
            field=models.CharField(help_text='Descripción del concepto', max_length=255),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='ventasweb_c_cliente_c4882b_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado'], name='ventasweb_c_estado_f5065c_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha_emision'], name='ventasweb_c_fecha_e_25ba1a_idx'),
        ),
    ]
