# Generated by Django 5.1.4 on 2026-08-29 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0066_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='firma_cliente',
            field=models.TextField(blank=True, help_text='Firma digital del cliente en base64', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='firma_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de firma', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='firma_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se firmó', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='token_publico',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ultimo_recordatorio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='veces_vista',
            field=models.IntegerField(default=0, help_text='Número de veces que se ha visto'),
        ),
        migrations.CreateModel(
            name='HistorialCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('cambio_estado', 'Cambio de Estado'), ('firma', 'Firma del Cliente'), ('conversion', 'Conversión a Factura'), ('envio', 'Envío al Cliente'), ('vista', 'Vista por Cliente')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción del cambio realizado')),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ventasweb.cotizacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cotización',
                'verbose_name_plural': 'Historiales de Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la plantilla', max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dias_vencimiento', models.IntegerField(default=30, help_text='Días de validez de la cotización')),
                ('terminos_condiciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Cotización',
                'verbose_name_plural': 'Plantillas de Cotización',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlantillaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasweb.articulo')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventasweb.plantillacotizacion')),
            ],
            options={
                'verbose_name': 'Detalle de Plantilla',
                'verbose_name_plural': 'Detalles de Plantilla',
                'ordering': ['orden'],
            },
        ),
    ]
