# Generated by Django 4.2.17 on 2026-08-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasweb', '0065_client_facturacion_electronica_and_more'),
        ('ventasweb', '0067_cotizacion_firma_cliente_cotizacion_firma_fecha_and_more'),
    ]

    operations = [
    ]
