"""
Django settings for Escuela project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
SESSION_COOKIE_AGE = 300  # 5 minutos
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Cambia a tu proveedor de correo
EMAIL_PORT = 587  # El puerto SMTP adecuado
EMAIL_USE_TLS = True  # Asegúrate de que TLS esté activado
EMAIL_HOST_USER = 'canadamelissa007@gmail.com'  # Tu dirección de correo
EMAIL_HOST_PASSWORD = 'acwh couw axzi vzof'  # Tu contraseña o un token de aplicación si usas Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SITE_URL = "127.0.0.1:8000" 




#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6ee57w85#js2o^3h+l3+-6s#s22du2op0kgv-=&=l_(+--38w$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'escuelaweb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Escuela.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [os.path.join(BASE_DIR, "escuelaweb", "templates")],  # Updated path
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Escuela.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import sys
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.append(os.path.dirname(os.path.abspath(__file__)))  # Agrega el directorio actual al path
import config  # Importa la configuración desde config.py

DATABASES = config.DATABASES  # Usa la configuración de PostgreSQL desde config.py


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators





AUTH_USER_MODEL = 'escuelaweb.CustomUser'





AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-do'  # Español - República Dominicana

TIME_ZONE = 'America/Santo_Domingo'  # Zona horaria República Dominicana (UTC-4)

USE_I18N = True

USE_TZ = True  # Mantener True para usar timezone-aware datetimes


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Ruta para recolectar archivos estáticos en producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use WhiteNoise to serve static files in development/production when configured
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Configuración de datos de la escuela para recibos
ESCUELA_NOMBRE = 'Centro Cristiano de Educación para el Desarrollo'
ESCUELA_RNC = '123-45678-9'
ESCUELA_TELEFONO = '(809) 555-1234'
ESCUELA_DIRECCION = 'Calle Pedro Henrriquez Ureña #123, San Juan de la Maguana, República Dominicana'
ESCUELA_EMAIL = 'info@escuela.edu.do'

